### ISSUE TITLE
dotnet new generated tools default json config uses incorrect function-handler when folder uses dashes

### ISSUE THREAD

**Issue by kientran** [aws/aws-lambda-dotnet#175] opened 2017-10-20 16:34 UTC
Amazon.Lambda.Tools Version 1.8.0

When using the command ```dotnet new lambda.EmptyFunction``` within a  folder that contains a dash, the tool will generate the ```aws-lambda-tools.defaults.json``` file with a function-handler that substituted the dash to an underscore for the package name.

Example:

```
mkdir dotnet-myproject
cd dotnet-myproject
dotnet new lambda.EmptyFunction
```

The result is

```
dotnet_myproject::dotnet_myproject.Function::FunctionHandler
```

While this is accurate for the namespace, by default the project name and package name used by dotnet's build will be the folder name with dashes.  This will generate the project dll with the file name of dashes.

If continuing with ```dotnet lambda deploy-function``` without correcting the tool's json file, the function will be deployed with an incorrect function handler leading to "file not found" errors.

It should be
```
dotnet-myproject::dotnet_myproject.Function::FunctionHandler
```

**Comment by normj** [comment] 2017-10-23 04:46
This is a duplicate of https://github.com/aws/aws-lambda-dotnet/issues/87. The short answer is there an issue with the dotnet templating engine that has a fix in the newer version of the dotnet CLI but it breaks existing templates. My plan was to make the shift to to the new templating syntax when the fix with the dotnet CLI becomes ubiquitous which is probably pretty soon.

**Comment by normj** [comment] 2017-12-23 09:42
Closing as duplicate

**Closed by normj** 2017-12-23 09:42 UTC
Labels: Question
