### ISSUE TITLE
AspNetCoreServer - Fails to bootstrap with "Native image cannot be loaded" exception

### ISSUE THREAD

**Issue by gruntruk** [aws/aws-lambda-dotnet#124] opened 2017-05-27 14:45 UTC
Hi, I'm having some trouble with trying to do a simple hello world deployment of Web API to Lambda and keep hitting `Native image cannot be loaded multiple times` exception when attempting to deploy my application.

Looking in cloud watch I see the following:

```
An exception was thrown when the constructor for type 'Cram.Lambda.LambdaFunction' was invoked. Check inner exception for more details.: LambdaException


at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
at System.Activator.CreateInstance(Type type, Boolean nonPublic)
at System.Activator.CreateInstance(Type type)
Exception has been thrown by the target of an invocation.: TargetInvocationException
at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at Microsoft.AspNetCore.Hosting.Internal.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection exportServices)
at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
at Amazon.Lambda.AspNetCoreServer.APIGatewayProxyFunction..ctor()
Native image cannot be loaded multiple times: FileLoadException
at Microsoft.Extensions.DependencyInjection.MvcRazorMvcCoreBuilderExtensions.AddRazorViewEngineServices(IServiceCollection services)
at Microsoft.Extensions.DependencyInjection.MvcRazorMvcCoreBuilderExtensions.AddRazorViewEngine(IMvcCoreBuilder builder)
at Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddMvc(IServiceCollection services)
```

My .csproj file (using dotnet 1.0.4) is as follows:

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp1.0</TargetFramework>
    <PreserveCompilationContext>false</PreserveCompilationContext>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.AspNetCoreServer" Version="0.10.1-preview1" />
    <PackageReference Include="Microsoft.AspNetCore" Version="1.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics" Version="1.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.1.3" />
    <PackageReference Include="Microsoft.AspNetCore.Routing" Version="1.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.Server.IISIntegration" Version="1.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="1.1.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.CommandLine" Version="1.1.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="1.1.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="1.1.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="1.1.2" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="1.1.2" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="1.1.2" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="1.1.2" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Amazon.Lambda.Tools" Version="1.4.0" />
  </ItemGroup>
</Project>
```

I'm unclear as to what the issue might be and did not find anything in prior issues. I was able to work around an earlier issue by adding the `<PreserveCompilationContext>false</PreserveCompilationContext>` which I uncovered in prior issues here. Has anyone encountered this before and might know how I've misconfigured something in my project setup? 

In case it is relevant, I'm using `serverless 1.14.0` to package the application which compiles as follows:

```bash
dotnet restore
dotnet publish -c release
```

Any help is appreciated. Thanks!

**Comment by normj** [comment] 2017-05-27 18:16
Looks like you are pulling in .NET Core 1.1 packages for ASP.NET Core. Lambda only supports .NET Core 1.0. Also if you update  Amazon.Lambda.Tools to version 1.5.0 when you run `dotnet lambda package -c release` instead of `dotnet publish -c release` you will get errors when you pull in .NET Core 1.1 references.

**Comment by gruntruk** [comment] 2017-05-30 15:47
Hi @normj, thank you for your help. I tried forcing to 1.0.x with the following csproj file structure:

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp1.0</TargetFramework>
    <PreserveCompilationContext>false</PreserveCompilationContext>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.AspNetCoreServer" Version="0.10.1-preview1" />
    <PackageReference Include="Microsoft.AspNetCore" Version="1.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics" Version="1.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Routing" Version="1.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Server.IISIntegration" Version="1.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="1.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.CommandLine" Version="1.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="1.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="1.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="1.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="1.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="1.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="1.0.0" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Amazon.Lambda.Tools" Version="1.5.0" />
  </ItemGroup>
</Project>
```

I deleted the lambda, wiped my local nuget cache at `~/nuget` restored, built and redeployed and continue to get the same `Native image cannot be loaded multiple times: FileLoadException` error however. I do see a number of build warnings when compiling (I'm on ubuntu dotnet 1.0.4):

```
 Restoring packages for /home/kris/projects/cram-lambda/src/Cram.Lambda/Cram.Lambda.csproj...
/usr/share/dotnet/sdk/1.0.4/NuGet.targets(97,5): warning : Dependency specified was Microsoft.AspNetCore (>= 1.0.0) but ended up with Microsoft.AspNetCore 1.0.3. [/home/kris/projects/cram-lambda/src/Cram.Lambda/Cram.Lambda.csproj]
/usr/share/dotnet/sdk/1.0.4/NuGet.targets(97,5): warning : Detected package downgrade: Microsoft.AspNetCore.Diagnostics from 1.0.1 to 1.0.0  [/home/kris/projects/cram-lambda/src/Cram.Lambda/Cram.Lambda.csproj]
/usr/share/dotnet/sdk/1.0.4/NuGet.targets(97,5): warning :  Cram.Lambda (>= 1.0.0) -> Microsoft.AspNetCore (>= 1.0.3) -> Microsoft.AspNetCore.Diagnostics (>= 1.0.1)  [/home/kris/projects/cram-lambda/src/Cram.Lambda/Cram.Lambda.csproj]
/usr/share/dotnet/sdk/1.0.4/NuGet.targets(97,5): warning :  Cram.Lambda (>= 1.0.0) -> Microsoft.AspNetCore.Diagnostics (>= 1.0.0) [/home/kris/projects/cram-lambda/src/Cram.Lambda/Cram.Lambda.csproj]
/usr/share/dotnet/sdk/1.0.4/NuGet.targets(97,5): warning : Detected package downgrade: Microsoft.AspNetCore.Routing from 1.0.2 to 1.0.0  [/home/kris/projects/cram-lambda/src/Cram.Lambda/Cram.Lambda.csproj]
/usr/share/dotnet/sdk/1.0.4/NuGet.targets(97,5): warning :  Cram.Lambda (>= 1.0.0) -> Microsoft.AspNetCore (>= 1.0.3) -> Microsoft.AspNetCore.Routing (>= 1.0.2)  [/home/kris/projects/cram-lambda/src/Cram.Lambda/Cram.Lambda.csproj]
/usr/share/dotnet/sdk/1.0.4/NuGet.targets(97,5): warning :  Cram.Lambda (>= 1.0.0) -> Microsoft.AspNetCore.Routing (>= 1.0.0) [/home/kris/projects/cram-lambda/src/Cram.Lambda/Cram.Lambda.csproj]
/usr/share/dotnet/sdk/1.0.4/NuGet.targets(97,5): warning : Detected package downgrade: Microsoft.AspNetCore.Server.IISIntegration from 1.0.1 to 1.0.0  [/home/kris/projects/cram-lambda/src/Cram.Lambda/Cram.Lambda.csproj]
/usr/share/dotnet/sdk/1.0.4/NuGet.targets(97,5): warning :  Cram.Lambda (>= 1.0.0) -> Microsoft.AspNetCore (>= 1.0.3) -> Microsoft.AspNetCore.Server.IISIntegration (>= 1.0.1)  [/home/kris/projects/cram-lambda/src/Cram.Lambda/Cram.Lambda.csproj]
/usr/share/dotnet/sdk/1.0.4/NuGet.targets(97,5): warning :  Cram.Lambda (>= 1.0.0) -> Microsoft.AspNetCore.Server.IISIntegration (>= 1.0.0) [/home/kris/projects/cram-lambda/src/Cram.Lambda/Cram.Lambda.csproj]
/usr/share/dotnet/sdk/1.0.4/NuGet.targets(97,5): warning : Detected package downgrade: Microsoft.AspNetCore.Server.Kestrel from 1.0.2 to 1.0.0  [/home/kris/projects/cram-lambda/src/Cram.Lambda/Cram.Lambda.csproj]
/usr/share/dotnet/sdk/1.0.4/NuGet.targets(97,5): warning :  Cram.Lambda (>= 1.0.0) -> Microsoft.AspNetCore (>= 1.0.3) -> Microsoft.AspNetCore.Server.Kestrel (>= 1.0.2)  [/home/kris/projects/cram-lambda/src/Cram.Lambda/Cram.Lambda.csproj]
/usr/share/dotnet/sdk/1.0.4/NuGet.targets(97,5): warning :  Cram.Lambda (>= 1.0.0) -> Microsoft.AspNetCore.Server.Kestrel (>= 1.0.0) [/home/kris/projects/cram-lambda/src/Cram.Lambda/Cram.Lambda.csproj]
/usr/share/dotnet/sdk/1.0.4/NuGet.targets(97,5): warning : Detected package downgrade: Microsoft.Extensions.Configuration.EnvironmentVariables from 1.0.1 to 1.0.0  [/home/kris/projects/cram-lambda/src/Cram.Lambda/Cram.Lambda.csproj]
/usr/share/dotnet/sdk/1.0.4/NuGet.targets(97,5): warning :  Cram.Lambda (>= 1.0.0) -> Microsoft.AspNetCore (>= 1.0.3) -> Microsoft.Extensions.Configuration.EnvironmentVariables (>= 1.0.1)  [/home/kris/projects/cram-lambda/src/Cram.Lambda/Cram.Lambda.csproj]
/usr/share/dotnet/sdk/1.0.4/NuGet.targets(97,5): warning :  Cram.Lambda (>= 1.0.0) -> Microsoft.Extensions.Configuration.EnvironmentVariables (>= 1.0.0) [/home/kris/projects/cram-lambda/src/Cram.Lambda/Cram.Lambda.csproj]
/usr/share/dotnet/sdk/1.0.4/NuGet.targets(97,5): warning : Detected package downgrade: Microsoft.Extensions.Configuration.FileExtensions from 1.0.1 to 1.0.0  [/home/kris/projects/cram-lambda/src/Cram.Lambda/Cram.Lambda.csproj]
/usr/share/dotnet/sdk/1.0.4/NuGet.targets(97,5): warning :  Cram.Lambda (>= 1.0.0) -> Microsoft.AspNetCore (>= 1.0.3) -> Microsoft.Extensions.Configuration.FileExtensions (>= 1.0.1)  [/home/kris/projects/cram-lambda/src/Cram.Lambda/Cram.Lambda.csproj]
/usr/share/dotnet/sdk/1.0.4/NuGet.targets(97,5): warning :  Cram.Lambda (>= 1.0.0) -> Microsoft.Extensions.Configuration.FileExtensions (>= 1.0.0) [/home/kris/projects/cram-lambda/src/Cram.Lambda/Cram.Lambda.csproj]
/usr/share/dotnet/sdk/1.0.4/NuGet.targets(97,5): warning : Detected package downgrade: Microsoft.Extensions.Configuration.Json from 1.0.1 to 1.0.0  [/home/kris/projects/cram-lambda/src/Cram.Lambda/Cram.Lambda.csproj]
/usr/share/dotnet/sdk/1.0.4/NuGet.targets(97,5): warning :  Cram.Lambda (>= 1.0.0) -> Microsoft.AspNetCore (>= 1.0.3) -> Microsoft.Extensions.Configuration.Json (>= 1.0.1)  [/home/kris/projects/cram-lambda/src/Cram.Lambda/Cram.Lambda.csproj]
/usr/share/dotnet/sdk/1.0.4/NuGet.targets(97,5): warning :  Cram.Lambda (>= 1.0.0) -> Microsoft.Extensions.Configuration.Json (>= 1.0.0) [/home/kris/projects/cram-lambda/src/Cram.Lambda/Cram.Lambda.csproj]
/usr/share/dotnet/sdk/1.0.4/NuGet.targets(97,5): warning : Detected package downgrade: Microsoft.Extensions.Logging from 1.0.1 to 1.0.0  [/home/kris/projects/cram-lambda/src/Cram.Lambda/Cram.Lambda.csproj]
/usr/share/dotnet/sdk/1.0.4/NuGet.targets(97,5): warning :  Cram.Lambda (>= 1.0.0) -> Microsoft.AspNetCore (>= 1.0.3) -> Microsoft.Extensions.Logging (>= 1.0.1)  [/home/kris/projects/cram-lambda/src/Cram.Lambda/Cram.Lambda.csproj]
/usr/share/dotnet/sdk/1.0.4/NuGet.targets(97,5): warning :  Cram.Lambda (>= 1.0.0) -> Microsoft.Extensions.Logging (>= 1.0.0) [/home/kris/projects/cram-lambda/src/Cram.Lambda/Cram.Lambda.csproj]
/usr/share/dotnet/sdk/1.0.4/NuGet.targets(97,5): warning : Detected package downgrade: Microsoft.Extensions.Logging.Console from 1.0.1 to 1.0.0  [/home/kris/projects/cram-lambda/src/Cram.Lambda/Cram.Lambda.csproj]
/usr/share/dotnet/sdk/1.0.4/NuGet.targets(97,5): warning :  Cram.Lambda (>= 1.0.0) -> Microsoft.AspNetCore (>= 1.0.3) -> Microsoft.Extensions.Logging.Console (>= 1.0.1)  [/home/kris/projects/cram-lambda/src/Cram.Lambda/Cram.Lambda.csproj]
/usr/share/dotnet/sdk/1.0.4/NuGet.targets(97,5): warning :  Cram.Lambda (>= 1.0.0) -> Microsoft.Extensions.Logging.Console (>= 1.0.0) [/home/kris/projects/cram-lambda/src/Cram.Lambda/Cram.Lambda.csproj]
```

I'm still not sure where I'm going wrong here and what is breaking.

**Comment by shingoaoyama1** [comment] 2017-06-03 11:29
Hi, I'm also getting the same error. My csproj file structure as follows:
WebApplication
```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp1.0</TargetFramework>
    <PreserveCompilationContext>false</PreserveCompilationContext>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.AspNetCoreServer" Version="0.10.1-preview1" />
    <PackageReference Include="Microsoft.AspNetCore" Version="1.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.0.4" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Amazon.Lambda.Tools" Version="1.6.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SoapCore\SoapCore.csproj" />
  </ItemGroup>
</Project>
```
Class library
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp1.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="1.0.4" />
    <PackageReference Include="System.ServiceModel.Http" Version="4.3.0" />
    <PackageReference Include="System.ServiceModel.Primitives" Version="4.3.0" />
    <PackageReference Include="System.Xml.XmlDocument" Version="4.3.0" />
    <PackageReference Include="System.Xml.XmlSerializer" Version="4.3.0" />
  </ItemGroup>
</Project>
```

**Comment by shingoaoyama1** [comment] 2017-06-04 07:53
OK, I found that the problem was the loggerFactory.AddConsole(); in the Startup class. Removing it resolved the issue.

**Comment by CameronFiederer** [comment] 2017-06-05 00:05
@shingoaoyama1 Thanks for the update, was running into the same issue, and this appears to fix it.

**Comment by IgorFedchenko** [comment] 2017-06-05 16:15
I had the same issue. After running `dotnet lambda package -c release` it turned out that targeting `netcoreapp1.0` in my project referenced `netstandard1.6.1` framework, while labmda supports only 1.6 version. So I managed to make it work with following steps:

1. Edit project file and changed `TargetFramework` from netcoreapp1.0 to netstandard1.6
2. To fix multiple issues with "namespace could not be found" I installed v1.6 via NuGet: `Install-Package NETStandard.Library -Version 1.6.0` (VS refused to just restore it with `dotnet restore`)
3. Edit all my project dependencies `TargetFramework` sections to also move them from netcoreapp1.0 to netstandard1.6

After that I managed to compile my project. `dotnet lambda package -c release` still failed to build project due to some errors about missing namespaces, and I had some warnings about package downgrades (1.6.0-1.6.1), but  `dotnet publish -c release` was working and I deployed service successfully.

But in this configuration Visual Studio 2017 refuses to run/debug project (to debug I need to switch back to netcoreapp1.0 target) - it gives `RunCommand property is not defined.` error. For now I am switching between targets, but definitely it is a temprorary solution. 

By the way, initially project template was using netcoreapp1.0 target and it worked well, so it looks like lambda failes during to some libraries call to netstandard 1.6.1 API, which is still ,net core 1.0 but is not suported by lambda.

@normj does this help in some way? Maybe the problem is that Lambda supports .NET Core 1.0, but not the latest version of it (1.6 instead of 1.6.1)? Are there any other ways to overcome this issues? I am not sure I did not make some unnecessary steps because I am relatively new to .NET Core system (used to work with .NET Full Framework).

**Comment by IgorFedchenko** [comment] 2017-06-05 16:17
Actually for now I am using this hack:

```
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <TargetFramework>netstandard1.6</TargetFramework>
    <OutputTypeEx>exe</OutputTypeEx>
    <ApplicationIcon />
    <StartupObject />
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <TargetFramework>netcoreapp1.0</TargetFramework>
    <OutputTypeEx>exe</OutputTypeEx>
    <ApplicationIcon />
    <StartupObject />
  </PropertyGroup>
```

This allows me relativelly easy do debug and deploy, but again this is a temprorary solution

**Comment by normj** [comment] 2017-06-05 23:29
Sorry this issue has gotten a little confusing for me to follow. Sounds like we are having a few different issues going on. If somebody has a sample project demonstrating the problem they can share that would be great help.

Versioning in .NET Core is very confusing right now but version 1.6.1 of .NETStandard.Library is part of the .NET Core 1.1 release. Some libraries that target .NETStandard.Library 1.6.1 might work depending on their usage of core dependencies but it is not reliable which is why the latest **Amazon.Lambda.Tools** blocks deployments that pull in .NETStandard.Library 1.6.1.

**Comment by IgorFedchenko** [comment] 2017-06-06 16:42
Ok... Well, I started to create simple project to reproduce the issue. I created a new one using AWS Serverless Application template (and selected ASP.NET Core option), then I just added my real project files like Startup and Controllers one by one, deploying each time and checking if project will stop working... But finally I restored the whole project and it is working normally (targeting netcoreapp1.0) without any special tricks. 

I have spent a few hours trying to find any meaningfull difference between projects, but still did not find anything that could be a root of a problem. But just taking all files from new project and pasting them to the old one helps, so for now I have to move forward (I have already spent few days with all this stuff). 

If I will meet this issue again in other projects, I will investigate it deeper.

**Comment by IgorFedchenko** [comment] 2017-06-10 13:03
Ok, now I have completely sorted out my issue.
I am using Swagger (Swashbuckle.AspNetCore package) to display online documentation for my lambda-hosted service. On my local machine all worked, but after deploying it was crashing with already mentioned exception (Native image could not be loaded...). After getting package sources (OpenSource is cool) and debugging with "Console.WriteLine" technique I have found that there was a real exception about missing XML doc file (it did not copy with `dotnet publish` or `dotnet lambda package` commands). 
I placed try...catch block with logging and rethrowing exception, and here is my log in CloudWatch:

`Swagger ERROR: System.IO.FileNotFoundException: Could not find file '/var/task/SampleService.xml'.
File name: '/var/task/SampleService.xml'
at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
at Interop.CheckIo[TSafeHandle](TSafeHandle handle, String path, Boolean isDirectory, Func`2 errorRewriter)
at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
at System.IO.UnixFileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
at System.IO.UnixFileSystem.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
at System.Xml.XmlSystemPathResolver.GetEntity(Uri uri, String role, Type typeOfObjectToReturn)
at System.Xml.XmlTextReaderImpl.FinishInitUriString()
at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
at System.Xml.XPath.XPathDocument..ctor(String uri, XmlSpace space)
at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenOptions.<>c__DisplayClass25_0.<IncludeXmlComments>b__0()
at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenOptions.CreateSwaggerProvider(IServiceProvider serviceProvider)

START RequestId: 90871711-4dd3-11e7-853d-ab90391b490f Version: $LATEST
An exception was thrown when the constructor for type 'SampleService.LambdaEntryPoint' was invoked. Check inner exception for more details.: LambdaException

at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
at System.Activator.CreateInstance(Type type, Boolean nonPublic)
at System.Activator.CreateInstance(Type type)
Exception has been thrown by the target of an invocation.: TargetInvocationException
at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at Microsoft.AspNetCore.Hosting.Internal.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection exportServices)
at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
at Amazon.Lambda.AspNetCoreServer.APIGatewayProxyFunction..ctor()
Native image cannot be loaded multiple times: FileLoadException
at Microsoft.Extensions.DependencyInjection.MvcRazorMvcCoreBuilderExtensions.AddRazorViewEngineServices(IServiceCollection services)
at Microsoft.Extensions.DependencyInjection.MvcRazorMvcCoreBuilderExtensions.AddRazorViewEngine(IMvcCoreBuilder builder)
at Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddMvc(IServiceCollection services)
at Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddMvc(IServiceCollection services, Action`1 setupAction)
at MobileGatewayService.Startup.ConfigureServices(IServiceCollection services)

END RequestId: 90871711-4dd3-11e7-853d-ab90391b490f
REPORT RequestId: 90871711-4dd3-11e7-853d-ab90391b490f Duration: 1212.72 ms Billed Duration: 1300 ms Memory Size: 1024 MB Max Memory Used: 55 MB `

I did not change packages versions to be 1.0.* (for example swagger nuget package references NETStandard.Library >= 1.6.1), did not change project target to something other then default netcoreapp1.0 - it was just a simple funny error.

**So my conclusion for now is**: `Native image cannot be loaded multiple times: FileLoadException` _means some other exception in your application during startup, and it looks like it is not related to your target framework version_.

P.S. Anyway I would recommend to set nuget project versions to be compatible with .NET Code 1.0 (not depend from .NETStandard.Library 1.6.1) - and `dotnet lambda package -c release` really helps. It is running on lambda without this checks anyway, but just to be safe from runtime craches.

P.P.S. But it would be much better if this exception was in CloudWatch log without placing debug output lines into specially downloaded package sources (but I am not sure this is an AWS Lambda problem)

**Comment by IgorFedchenko** [comment] 2017-06-21 14:21
And about the issue with `loggerFactory.AddConsole();` - no need to remove this statement. Just change the version of the corresponding package (`Microsoft.Extensions.Logging.Console` in this case) from 1.1.* to 1.0.* (from 1.1.2 to 1.0.2 in my case) - so that is was not referencing NETStandard.Library 1.6.1 (I am usually checking dependencies on the package's NuGet page).

**Comment by normj** [comment] 2017-07-07 20:24
I'm closing this as I believe the main issues have been resolved. Versioning does continue to be a challenge with .NET Core and Lambda and we will look to find ways to make this better in the future.

**Closed by normj** 2017-07-07 20:24 UTC
Labels: Question

**Comment by jsousa411** [comment] 2017-07-15 20:57
This helped me keep going with my project, "...change the version of the corresponding package (Microsoft.Extensions.Logging.Console in this case) from 1.1.* to 1.0.* (from 1.1.2 to 1.0.2 in my case) - so that is was not referencing NETStandard.Library 1.6.1 (I am usually checking dependencies on the package's NuGet page)."  Thanks!

**Comment by djaquez** [comment] 2017-08-21 15:23
I wanted to add a statement as a note to anybody seeing "Native image cannot be loaded multiple times: FileLoadException" when MVC is being added to the services in Startup.ConfigureServcies.

This exception is thrown but it really is a red herring.  Catch the exception and handle it.  That will allow your application to log the true exception that is causing the real problem.

In my case, I had a null reference exception in my code that caused this exception to be thrown.  I was not able to tell what the issue was because I didn't think my code (where the null was) was being run. But it was!  Once I handled this exception I was able to see and fix my null reference exception and this exception went away as well.

**Comment by FrederikNygaardSvendsen** [comment] 2017-10-17 14:52
@IgorFedchenko Did you manage to solve your swagger problem? I'm having the exact same issue :-)

**Comment by jsousa411** [comment] 2017-10-17 15:12
I did manage to fix my problem.  Let me know if you're having issues.
 I'll b willing to do a team viewer session to hep out.

**Comment by FrederikNygaardSvendsen** [comment] 2017-10-17 15:46
@jsousa411 Thank you so much for the offer, but just managed to get it working. Cheers

**Comment by abidalis** [comment] 2017-11-18 13:52
@FrederikNygaardSvendsen and @jsousa411 I'm too having the issue with swagger. I can able to add swagger to api using Swashbuckle and can access the API documentation in local environment using **/swagger** endpoint. When i deployed the API on AWS APIGateway, I'm getting 403 forbidden error for **/swagger** endpoint. In Cloudwatch error logged 

> [Debug] Microsoft.AspNetCore.Builder.RouterMiddleware: Request did not match any routes. 

However the other endpoint like GET, POST requests are working fine.

Could you please help me to setup API help using swagger?

Thanks.
