### ISSUE TITLE
Libc call mlock failed with result -1 12 

### ISSUE THREAD

**Issue by lyricnz** [aws/aws-lambda-dotnet#701] opened 2020-07-19 22:54 UTC
## Description
Hi. Attempting to use a SecureMemory implementation on .NET core 2.1 on AWS Lambda, that uses libc+mlock under the covers. Periodically this fails with an error from libc/mlock "Libc call mlock failed with result -1 12"

## Reproduction Steps
Run application for a bit. Sometimes it fails immediately.  The Lambda reports MemoryUsedInMB at 132 of 1024.  
App uses https://github.com/godaddy/asherah

### Logs
See https://github.com/godaddy/asherah/issues/260

errno 12 is "12 ENOMEM Cannot allocate memory.  The new process image required more memory than was allowed by the hardware or by system-imposed memory management constraints.  A lack of swap space is normally temporary; however, a lack of core is not.  Soft limits may be increased to their corresponding hard limits."

### Environment
.NET core 2.1 on AWS Lambda

---

This is a :bug: bug-report

**Comment by lyricnz** [comment] 2020-07-20 09:16
Same happens on .NET core 3.1

**Comment by NGL321** [comment] 2020-07-22 01:58
Hi @lyricnz,

Thank you for reporting this. Could you provide the code from the lambda you are attempting to run that fails with the stated error? (if you are not able to share exactly, a general mockup of your code should be fine) 
At first glance this seems like a problem with the encryption library rather than the lambda, but I can attempt to reproduce if you provide some more information.

😸 😷

**Comment by lyricnz** [comment] 2020-07-22 02:28
The library that we are using was linked above - https://github.com/godaddy/asherah  (and the linked defect includes a stack trace through their code)
The code that triggers this ultimately calls libc mlock:

```
[DllImport("libc", EntryPoint = "mlock", SetLastError = true)]
        private static extern int _mlock(IntPtr start, size_t len);

        public int mlock(IntPtr start, size_t len)
        {
            return _mlock(start, len);
        }
```

Which fails with a -1 / errno=12

**Comment by lyricnz** [comment] 2021-10-03 00:44
This is still an issue for us. The bottom-line is that AWS-lambda has very limited mlock-able memory (64KB in 4KB pages), which creates problems for applications that attempt to protect memory for paging.

**Comment by ashishdhingra** [comment] 2023-12-04 22:40
@lyricnz Could you please confirm if this is still an issue with latest version of .NET runtime?

**Comment by ashishdhingra** [comment] 2024-07-24 23:29
Closing this issue due to lack of traction. Feel free to open a new issue in case scenario is reproducible in latest .NET Lambda runtime.

**Closed by ashishdhingra** 2024-07-24 23:29 UTC
Labels: bug, needs-reproduction, module/lambda-client-lib, queued, p2
