### ISSUE TITLE
ForEach-Object -Parallel no longer working in AWS PowerShell Lambda function.

### ISSUE THREAD

**Issue by donovan-middleton** [aws/aws-lambda-dotnet#1341] opened 2022-10-20 17:01 UTC
### Describe the bug

I updated from version 2.1.0.0 of the AWSPowerShellLambda module using the dotnetcore3.1 runtime to the latest (3.0.1.0) that now uses the dotnet6 runtime. I took the same PowerShell code and republished it so I would stay at a supported version and have found that it is now failing. I have narrowed the issue down to the use of the ForEach-Object -Parallel commands, so I have been experimenting. Publishing the following simplified code as a Lambda function fails when attempting to run it:

1..10 | ForEach-Object -Parallel {
    Write-Host $_
}

### Expected Behavior

The script block for the "ForEach-Object -Parallel" statement within the AWS Lambda function for the .net6 runtime would process as in the dotnet3.1 runtime without error.

### Current Behavior

Throws an error when running a test error message of:

{
  "errorType": "Write-Host",
  "errorMessage": "Write-Host",
  "stackTrace": [
    "at Amazon.Lambda.PowerShellHost.PowerShellFunctionHost.ExecuteFunction(Stream inputStream, ILambdaContext context)",
    "at lambda_method1(Closure , Stream , ILambdaContext , Stream )",
    "at Amazon.Lambda.RuntimeSupport.Bootstrap.UserCodeLoader.Invoke(Stream lambdaData, ILambdaContext lambdaContext, Stream outStream) in /src/Repo/Libraries/src/Amazon.Lambda.RuntimeSupport/Bootstrap/UserCodeLoader.cs:line 145",
    "at Amazon.Lambda.RuntimeSupport.HandlerWrapper.<>c__DisplayClass8_0.<GetHandlerWrapper>b__0(InvocationRequest invocation) in /src/Repo/Libraries/src/Amazon.Lambda.RuntimeSupport/Bootstrap/HandlerWrapper.cs:line 56",
    "at Amazon.Lambda.RuntimeSupport.LambdaBootstrap.InvokeOnceAsync(CancellationToken cancellationToken) in /src/Repo/Libraries/src/Amazon.Lambda.RuntimeSupport/Bootstrap/LambdaBootstrap.cs:line 176"
  ]
}

CloudWatch logs show the following message 10 times:

[Error] - The term 'Write-Host' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

### Reproduction Steps

Create a PowerShell script with the following code and publish it as a Lambda function using the Publish-AWSPowerShellLambda command from the AWSLambdaPSCore 3.0.1.0 module.

1..10 | ForEach-Object -Parallel {
    Write-Host $_
}

### Additional Information/Context

"For-Each -Parallel" worked in the 2.1.0.0 release.

### AWS .NET SDK and/or Package version used

AWS .NET 6.0.110 SDK
AWSLambdaPSCore 3.0.1.0
PowerShell 7.2.6

### Targeted .NET Platform

.NET 6

### Operating System and version

Windows 11 Pro

**Comment by ashishdhingra** [comment] 2022-10-20 19:05
Hi @donovan-middleton,

Good morning.

Thanks for reporting the issue. You seem to get the error `The term 'Write-Host' is not recognized as a name of a cmdlet, function, script file, or executable program.` in your CloudWatch logs when used inside a `ForEach-Object -Parallel`.

Observations:
- Able to reproduce the issue using your script and see the errors `[Error] - The term 'Write-Host' is not recognized as a name of a cmdlet, function, script file, or executable program.` logged in CloudWatch.
- Using simple script like `Write-Host "Testing..."` appears to works.
- Using `ForEach-Object` without `-Parallel` parameter appears to work.
- Looks like **none** of the `Write-Output`, `Write-Error` and `Write-Host` inside the `ForEach-Object -Parallel` work.
```PowerShell
1..10 | ForEach-Object -Parallel {
    Write-Output "Output: $_"
    Write-Error "Error: $_"
    Write-Host $_
}
```

Not sure if something changed in the .NET 6 runtime. This needs review with the team.

In the meanwhile, could you please share your use case where you need to simply write logging statements as part of `ForEach-Object -Parallel`? You could get into issues where messages logged to CloudWatch could get lost since these are pushed as part of separate thread.

Thanks,
Ashish

**Comment by donovan-middleton** [comment] 2022-10-20 19:37
We have a custom Lambda function tor starting and stopping instances that also utilize maintenance windows. I use the ForEach-Parallel to process starting, stopping, hibernating, and tagging instances. I only log if there is an issue with the command within the script block...  I use something along the lines of:

$EC2InstanceIDs | ForEach-Object -Parallel {
    Try {
        Start-EC2Instance -InstanceId $_
    } Catch {
        Write-Warning -Message ('Unable to start: ' + $Local:InstanceIdToStart + ' <-- ' + $($Error[0].Exception.Message))
    }
}

The logging helps us troubleshoot when we have an issue with one of the instances at a glance. But the logging had nothing to do with it... ANY code I put in the "For-EachObject -Parallel" statement was failing, even those without any Write statements at all. I just put the Write statement as a simple example to show how it was not working.

Thanks,
Donovan

**Comment by rborunda-jack** [comment] 2022-11-11 20:13
Any update on this ticket. I am running in to the same "write-host" error. I'm running in to the same issue.

**Comment by donovan-middleton** [comment] 2023-02-23 22:05
I haven't seen an update to the [AWSLambdaPSCore module](AWSLambdaPSCore) that might address this yet. And since AWS Lambda support for [.NET 3.1 ends on Apr 3, 2023](https://docs.aws.amazon.com/lambda/latest/dg/lambda-powershell.html) even though Microsoft Support for [.NET 3.1 ended on Dec 13, 2022](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core)... I have had to start exploring alternatives.

The alternative I am currently looking at is AWS Server Application Model (SAM). I found information on it in this blog post:
[Introducing the PowerShell custom runtime for AWS Lambda](https://aws.amazon.com/blogs/compute/introducing-the-powershell-custom-runtime-for-aws-lambda/). The article has links in there with some starter examples.

Playing around with it long enough, I finally figured it out enough to get my PowerShell function published in Lambda... And this method does not appear to have the same issue with the `ForEach-Object -Parallel` statement that the current method of publishing currently has!

Just a note of caution for anyone else trying SAM: The Lambda layer for the PowerShell Runtime Layer only works with PowerShell LTS version (currently 7.2.9). For some reason PowerShell 7.3 does NOT work in the PowerShell Runtime Layer. Apparently that is a known issue. You can get the latest PowerShell versions on GitHub here: [https://github.com/powershell/powershell#get-powershell](https://github.com/powershell/powershell#get-powershell)

Really hoping the AWSLambdaPSCore module gets updated to address this before .NET 3.1 is no longer supported though!!!

**Comment by erosen03** [comment] 2023-06-08 22:29
I'm experiencing the same issue. Are there any updates? It's been almost 1 year since the issue was originally reported.

**Comment by donovan-middleton** [comment] 2023-06-12 15:57
I've had to resort to using AWS Server Application Model (SAM) as there has been no movement on this issue. This issue is 1 of 12 "P1" issues in their stack... And it is the newest! Most are also marked as a "bug" and "queued", so I'm not expecting a resolution anytime soon. For me to continue to use it, I had to have a solution that provided a supported way forward with the runtime.

One benefit of AWS SAM is that it allows me to use the Editor to edit my Lambda function from the console! Using it isn't bad once you figure it out.

**Comment by ashishdhingra** [comment] 2023-06-28 23:56
@donovan-middleton Good afternoon. The issue was identified in the underlying .NET CLI Extensions tooling and has been fixed in `Amazon.Lambda.Tools` version `5.7.2`. Assuming you are using the latest version of `AWS Lambda Tools for Powershell` (refer [Readme](https://github.com/aws/aws-lambda-dotnet/tree/master/PowerShell)) for installation instructions), you should be able to leverage the fix automatically. Please verify the scenario at your end.

Thanks,
Ashish

**Comment by erosen03** [comment] 2023-06-29 06:05
Thanks for the update, @ashishdhingra. I can confirm the ForEach-Object -Parallel now works in our AWS PowerShell Lambda functions. After updating `Amazon.Lambda.Tools` to version `5.7.2` on the dev machine, it is necessary to rebuild and deploy the lambda function Zip package.

**Comment by ashishdhingra** [comment] 2023-06-29 16:20
> Thanks for the update, @ashishdhingra. I can confirm the ForEach-Object -Parallel now works in our AWS PowerShell Lambda functions. After updating Amazon.Lambda.Tools to version 5.7.2 on the dev machine, it is necessary to rebuild and deploy the lambda function Zip package.

@erosen03 Thanks for the confirmation. `Publish-AWSPowerShellLambda` should update the .NET CLI Extensions tooling automatically to latest version before deployment.

**Closed by ashishdhingra** 2023-06-29 16:20 UTC
Labels: bug, response-requested, module/custom-runtime, p1, queued
