### ISSUE TITLE
Unable to get the LambdaTestTool to find the assembly that needs to be debugged when using multiple projects.

### ISSUE THREAD

**Issue by geedsen** [aws/aws-lambda-dotnet#1235] opened 2022-07-08 09:43 UTC
### Describe the bug

Unable to get the LambdaTestTool to find the assembly that needs to be debugged

### Expected Behavior

Debugging starts in the correct assembly

### Current Behavior

It always errors that it cannot load the assembly

### Reproduction Steps

Have a solution with multiple projects, for example 
1) Project.Api
2) Project.Lambda
And Project.Lambda has a dependency on Project.Api.

When compiling, the bin\debug\net6 directory for Project.Lambda contains a  Project.Api.deps.json AND a Project.Lambda.deps.json.
The tools picks up the Project.Api.deps.json (FirstOrDefault) and can therefor never find the Project.Lambda.dll assembly

### Additional Information/Context

Workaround is to delete the not required *.deps.json files from the directory before running the tool.

### AWS .NET SDK and/or Package version used

AWSSDK.Lambda 3.7.13.18

### Targeted .NET Platform

NET6

### Operating System and version

Window 10

**Comment by ashishdhingra** [comment] 2022-07-08 16:02
Hi @geedsen,

Good morning.

Thanks for reporting the issue. Could you please share the sample code solution for reproduction? Also request you to add proper issue title for easy tracking. :blush:

Thanks,
Ashish

**Comment by geedsen** [comment] 2022-07-09 11:42
Sorry, I dont have a sample, Just production code. Could you not reproduce it?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ashishdhingra** [comment] 2022-07-11 23:15
@geedsen Somehow, I'm unable to reproduce the issue. Used Visual Studio 2022 and `Empty Lambda Function` project template to create the Lambda project, and added `Project.Api` class library project. Used `AWS .NET Core 6.0 Mock Lambda Test Tool (0.12.3)` for debugging.
**Project.Api.csproj**
```XML
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
```
**Project.Api.Operations**
```C#
namespace Project.Api
{
    public class Operations
    {
        public static int Add(int x, int y) => x + y;
    }
}
```
**Project.Lambda.csproj**
```XML
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <AWSProjectType>Lambda</AWSProjectType>
    <!-- This property makes the build directory similar to a publish directory and helps the AWS .NET Lambda Mock Test Tool find project dependencies. -->
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <!-- Generate ready to run images during publishing to improve cold start time. -->
    <PublishReadyToRun>true</PublishReadyToRun>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.Core" Version="2.1.0" />
    <PackageReference Include="Amazon.Lambda.Serialization.SystemTextJson" Version="2.3.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Project.Api\Project.Api.csproj" />
  </ItemGroup>
</Project>
```
**Project.Lambda.Function**
```C#
using Amazon.Lambda.Core;
using Project.Api;

// Assembly attribute to enable the Lambda function's JSON input to be converted into a .NET class.
[assembly: LambdaSerializer(typeof(Amazon.Lambda.Serialization.SystemTextJson.DefaultLambdaJsonSerializer))]

namespace Project.Lambda;

public class Function
{
    
    /// <summary>
    /// A simple function that takes a string and does a ToUpper
    /// </summary>
    /// <param name="input"></param>
    /// <param name="context"></param>
    /// <returns></returns>
    public string FunctionHandler(string input, ILambdaContext context)
    {
        return input.ToUpper() + Operations.Add(1, 2);
    }
}
```
**aws-lambda-tools.defaults.json**
```JSON
{
  "Information": [
    "This file provides default values for the deployment wizard inside Visual Studio and the AWS Lambda commands added to the .NET Core CLI.",
    "To learn more about the Lambda commands with the .NET Core CLI execute the following command at the command line in the project root directory.",
    "dotnet lambda help",
    "All the command line options for the Lambda command can be specified in this file."
  ],
  "profile": "default",
  "region": "us-east-2",
  "configuration": "Release",
  "function-runtime": "dotnet6",
  "function-memory-size": 256,
  "function-timeout": 30,
  "function-handler": "Project.Lambda::Project.Lambda.Function::FunctionHandler"
}
```

**Output:**
<img width="1558" alt="Screen Shot 2022-07-11 at 4 14 24 PM" src="https://user-images.githubusercontent.com/67916761/178374173-35cd2ea7-7255-4cd2-88b1-305149333431.png">

Thanks,
Ashish

**Comment by normj** [comment] 2022-07-19 00:33
I was able to reproduce the problem. I'm assuming @geedsen that `Project.Api` is an executable project which is causing multiple `deps.json` files to be written.

The test tool should prioritize the `deps.json` file that matches the name of the assembly specified in the function handler string.

**Comment by Simonl9l** [comment] 2022-07-20 00:25
@normj sees this is also related to https://github.com/aws/aws-lambda-dotnet/issues/1249 - in that the assembly for each handler is know from the `"Hander"` in the `serverless.template` as stored as part of the `LambdaFunctionInfo`.

**Comment by iabdelkareem** [comment] 2022-12-15 15:25
+1 Experiencing the same problem.

**Comment by rpgeddam** [comment] 2023-02-13 18:33
> [...] bin directory ends up with four different .deps.json files. So under what condition are they created and copied to the destination directory?

FWIW, this seems to be an issue with .NET tooling rather than aws-lambda-dotnet tooling. If you run good ol' `dotnet publish` in the downstream `.Lambda` project, it creates two *.deps.json files in the `bin` directory. This only happens with .NET SDK 6.0.x

I have a project that produces 1 .deps file with sdk 3.1.x and 2 .deps files with sdk 6.0.x with no changes to the project itself.

**Comment by normj** [comment] 2023-07-27 22:22
@rickdgray-dc We have a couple more PRs that are almost done and then we will make a release with all of the changes.

**Comment by normj** [comment] 2023-08-02 23:16
Version [0.14.0](https://github.com/aws/aws-lambda-dotnet/blob/master/RELEASE.CHANGELOG.md#release-2023-08-02) of the tool has been released with the fix.

**Closed** 2023-08-03 16:31 UTC
Labels: bug, module/lambda-test-tool, p1, queued

**Comment by jakebanks** [comment] 2024-09-25 23:43
I encountered this when I had renamed a project that was previously working with the test tool. The outdated *.deps.json were still around and the provided workaround in the OP helped, thanks.
