### ISSUE TITLE
Cannot install AWSLambdaPSCore in docker

### ISSUE THREAD

**Issue by bo67192** [aws/aws-lambda-dotnet#564] opened 2020-01-13 22:13 UTC
I've tried to install AWSLambdaPSCore on two different docker containers from the microsoft managed powershell repo

https://github.com/PowerShell/PowerShell-Docker#examples

6.2.3-nanoserver-1803
latest (on 1.13.2020)

On latest (ubuntu based) I get

```
PackageManagement\Install-Package : The module 'AWSLambdaPSCore' cannot be installed or updated because the authenticode signature of the file 'AWSLambdaPSCore.psd1' is not valid.
At C:\program files\powershell\Modules\PowerShellGet\PSModule.psm1:9508 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (Microsoft.PowerShel\u2026lets.InstallPackage:InstallPackage) [Install-Package], Exception
+ FullyQualifiedErrorId : InvalidAuthenticodeSignature,ValidateAndGet-AuthenticodeSignature,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
```

On server nano I get

```
PS C:\> install-module AWSLambdaPSCore -SkipPublisherCheck -Verbose
VERBOSE: Using the provider 'PowerShellGet' for searching packages.
VERBOSE: The -Repository parameter was not specified.  PowerShellGet will use all of the registered repositories.
VERBOSE: Getting the provider object for the PackageManagement Provider 'NuGet'.
VERBOSE: The specified Location is 'https://www.powershellgallery.com/api/v2' and PackageManagementProvider is 'NuGet'.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='AWSLambdaPSCore'' for ''.
VERBOSE: Total package yield:'1' for the specified package 'AWSLambdaPSCore'.
VERBOSE: Skipping installed module AWSLambdaPSCore 1.2.0.0.
```

But when I try to run

```
Get-AWSPowerShellLambdaTemplate
```
the command isn't found.

Any suggestions on what I can do? I'm trying server core now.

**Comment by bo67192** [comment] 2020-01-13 22:16
I realize this might be a powershell container problem. I'll go there next if this isn't related to the AWS module

**Comment by ashishdhingra** [comment] 2020-11-05 00:16
Duplicate of https://github.com/aws/aws-tools-for-powershell/issues/130

**Closed by ashishdhingra** 2020-11-05 00:16 UTC
Labels: bug, confusing-error, duplicate
