### ISSUE TITLE
Order of Cookie is getting changed when response is returned from Lambda when set as target against ALB

### ISSUE THREAD

**Issue by ElectricVampire** [aws/aws-lambda-dotnet#1414] opened 2023-01-19 08:57 UTC
### Describe the bug

In my code I am deleting the cookie before setting the new value for it.

// Code executed on 19th Jan
HttpContext.Response.Cookies.Delete("testCookie");
HttpContext.Response.Cookies.Append("testCookie", "test" , option);

Now I should see following in response in browser -
```
Set-Cookie  testCookie=; expires=Thu, 18 Jan 2023 18:33:48 GMT; path=/                        
Set-Cookie  testCookie=test; expires=Thu, 19 Jan 2023 18:33:48 GMT; path=/
```

This set `testCookie` to value `test` and returned in subsequent request.

Above is the behavior of my code when hosted on prem and EKS.

Now when hosted the code in lambda - 
Now I see following in response in browser -
```
Set-Cookie  testCookie=test; expires=Thu, 19 Jan 2023 18:33:48 GMT; path=/
Set-Cookie  testCookie=; expires=Thu, 18 Jan 2023 18:33:48 GMT; path=/  
```                      

This set `testCookie` to value empty which is also expired and  not returned in subsequent request.

https://github.com/aws/aws-lambda-dotnet/blob/master/Libraries/src/Amazon.Lambda.AspNetCoreServer/ApplicationLoadBalancerFunction.cs#L167

Here we are moving the headers from HeaderDictionary to IDictionary does this modify the order of cookies with same name?

### Expected Behavior

I should see the cookie in response header in same order in which they were set.

### Current Behavior

Order of cookie is getting changed

### Reproduction Steps

Host an API in ALB and set delete the of cookie and then set the same value. You will issue getting reproduced.

### AWS .NET SDK and/or Package version used

Amazon.Lambda.AspNetCoreServer.7.2.0

### Targeted .NET Platform

.NET 6

### Operating System and version

AmazonLinux - Lambda

**Comment by ashishdhingra** [comment] 2023-01-19 21:51
@ElectricVampire Thanks for reporting the issue. Could you please share the following:
- Your use case, why not just set the cookie with new value and expiration rather than deleting it first.
- Sample code solution which reproduces the issue, just want to make sure we have consistent repro.

Thanks,
Ashish

**Comment by ElectricVampire** [comment] 2023-01-20 16:15
1. Our application is multi layer application and in request/response pipeline there are various component not owned by our team. One of such component clears all the cookies for their own business logic and security concerns. But we are up in the pipeline hence we add the latest value to cookie.
2. I created code from Lambda Web API template and just added deleted cookies in Values controller Get method to reproduce the issue. https://github.com/ElectricVampire/LambdaWebApi.

**Comment by ElectricVampire** [comment] 2023-01-20 16:23
awselb/2.0 Headers in Browser :
Set-Cookie  testCookie=ABC; 
Set-Cookie  testCookie=;
Set-Cookie  dummy=abc;

Kestrel Headers in Browser 
Set-Cookie  dummy=abc;
Set-Cookie  testCookie=;
Set-Cookie  testCookie=ABC;

**Comment by ashishdhingra** [comment] 2024-09-24 18:45
**Findings:**
- Code for [ApplicationLoadBalancerResponse MarshallResponse()](https://github.com/aws/aws-lambda-dotnet/blob/master/Libraries/src/Amazon.Lambda.AspNetCoreServer/ApplicationLoadBalancerFunction.cs#L167) uses generic `new Dictionary<TKey,TValue>`.
- In a regular [Dictionary<TKey,TValue>](http://msdn.microsoft.com/en-us/library/xfhwa508.aspx), neither the keys nor values are maintained in any order. In a [SortedDictionary<TKey,TValue>](http://msdn.microsoft.com/en-us/library/f7fta44c.aspx) the keys and values are maintained in order by the value of the key - this is not the same as insertion order.
- The only built-in dictionary in the .NET framework that preserves insertion order is [System.Collections.Specialized.OrderedDictionary](http://msdn.microsoft.com/en-us/library/system.collections.specialized.ordereddictionary.aspx), but this class is not generic.
- Generic [OrderedDictionary<TKey,TValue>](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.ordereddictionary-2?view=net-9.0) is planned to be available in .NET 9.
 
  The only workaround is to build a generic wrapper around [System.Collections.Specialized.OrderedDictionary](http://msdn.microsoft.com/en-us/library/system.collections.specialized.ordereddictionary.aspx).

**Comment by ashishdhingra** [comment] 2024-09-30 22:34
When testing against `Amazon.Lambda.AspNetCoreServer.APIGatewayProxyFunction` (set as the base class in `LambdaEntryPoint`, the order of setting cookies is below in `ValuesController`:
```C#
...
        // GET api/values
        [HttpGet]
        public IEnumerable<string> Get()
        {
            var response = _httpContextAccessor.HttpContext.Response;
            response.Cookies.Append("dummy", "abc");
            response.Cookies.Delete("testCookie");
            response.Cookies.Append("testCookie", "ABC");

            return new string[] { "value1", "value2" };
        }
...
```
The order of cookie as viewed in browser developer tools is below:
<img width="1426" alt="Screenshot 2024-09-30 at 3 33 29 PM" src="https://github.com/user-attachments/assets/a906f5fe-2b36-4491-8b97-8e463103246e">

**Comment by ashishdhingra** [comment] 2024-10-10 16:24
@ElectricVampire As noted in previous comment, there is a below note at [Responses with multi-value headers](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/lambda-functions.html#multi-value-headers-response):
```
The load balancer might send the headers to the client in a different order than the order specified in the Lambda response payload. Therefore, do not count on headers being returned in a specific order.
```

So we should not be relying on the cookie order for ALB. Although I have opened a ticket with ALB team and awaiting response, most likely this behavior would not be changed. Hence, closing this ticket since the behavior is controlled by ALB environment. I will post updates, if any, as I receive from the ALB team.

Thanks,
Ashish

**Closed by ashishdhingra** 2024-10-10 16:24 UTC
Labels: bug, module/aspnetcore-support, queued, p2
