### ISSUE TITLE
Are Razor Pages supported?

### ISSUE THREAD

**Issue by genifycom** [aws/aws-lambda-dotnet#48] opened 2017-01-30 00:32 UTC
Hi Norm,

Is it possible to invoke MVC routes like /home/about via Lambda? /api/values of course works fine but right now /home/about return an error 500. Is invoking the MVC razor path even possible through Lambda (since it will return HTML rather than JSON)?

Thanks,

Dave

**Comment by normj** [comment] 2017-01-30 18:55
I tried to return back Razor pages the other day and the Roslyn compiler was having trouble finding assemblies. Is that the same error you see in your CloudWatch Logs? Its something I want to get working but I haven't had time yet to do deeper research.

**Comment by genifycom** [comment] 2017-01-30 21:31
Is there a way to pull the whole stack trace in one go from CloudWatch? Or just line by line?

Line by line the stack trace is:

System.InvalidOperationException: Can not find compilation library location for package 'AWSMVC'
at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths()
at System.Linq.Enumerable.<SelectManyIterator>d__157`2.MoveNext()
at Microsoft.AspNetCore.Mvc.Razor.Compilation.MetadataReferenceFeatureProvider.PopulateFeature(IEnumerable`1 parts, MetadataReferenceFeature feature)
at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRoslynCompilationService.GetCompilationReferences()
at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRoslynCompilationService.get_CompilationReferences()
at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRoslynCompilationService.Compile(RelativeFileInfo fileInfo, String compilationContent)
at Microsoft.AspNetCore.Mvc.Razor.Internal.CompilerCache.CreateCacheEntry(String relativePath, String normalizedPath, Func`2 compile)

**Comment by genifycom** [comment] 2017-02-01 15:25
So from the trace it looks like PopulateFeature cannot find or has the wrong path. Is there anything I can do to help? Please let me know.
BTW: https://github.com/aspnet/Tooling/issues/852 might have some similarities?

**Comment by joel-cunningham** [comment] 2017-02-09 14:35
I would like to invoke razor views from API Gateway as well and am getting the same exception.

```
An unhandled exception has occurred: Can not find compilation library location for package 'ApiGateway'
System.InvalidOperationException: Can not find compilation library location for package 'ApiGateway'
at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths()
```

Is there any guidance on how to fix this or possibly a feature to support razor views?

**Comment by normj** [comment] 2017-02-09 18:31
Sorry not yet.

**Comment by genifycom** [comment] 2017-02-18 18:38
Hi Norm,

Did you get a change to look at the Razor issue? I know there is a lot going on, but this one is a watershed. 
Will it be resolvable or is this a much bigger issue?

Thanks,
Dave

**Comment by normj** [comment] 2017-02-21 22:15
Hi Dave

We are still working on the issue. I'm hopeful it is resolvable but it is going to take some time.

Norm

**Comment by genifycom** [comment] 2017-02-24 17:28
Ok, ready to test it when you have it ready :-)

**Comment by ebekker** [comment] 2017-03-11 15:46
Suggest renaming the issue to something more descriptive like *Are Razor Pages supported?*

**Comment by slang25** [comment] 2017-03-11 15:58
It might be worth testing it with pre-compiled razor views, take the burden away from the runtime.

**Comment by normj** [comment] 2017-03-13 21:08
@ebekker Agreed on the renaming

@slang25  I believe pre-compiled is only supported in .NET Core 1.1


Today Lambda pushed out a fix for loading dynamic Assemblies which was part of the problem. We have a couple more changes we need to get on the service side before Razor pages will work but we are making progress.

**Comment by nosider** [comment] 2017-03-15 05:02
Hi,

While trying to get around the Lambda's dynamic assembly loading limitation by embedding the cshtml views into the library itself and then serving them from the embedded resource, I am hitting a roadblock when RazorViewEngine tries to compile the cshtml. 

The error is a `TypeInitializationException`, thrown when initialising `Microsoft.Extensions.DependencyModel.CompilationLibrary`. It is thrown when `RuntimeEnvironment` is initialising it's static fields. The underlying cause seems to be that the `Microsoft.DotNet.PlatformAbstractions.RuntimeEnvironment` is throwing a `System.PlatformNotSupportedException` when trying to resolve the OS.

I have replicated the issue by Referencing any field or method in the `Microsoft.DotNet.PlatformAbstractions.RuntimeEnvironment`. This happens only when the code is running in Lambda, but not Locally or in Docker.

Does anyone know if there is a way to work-around this issue?

Cheers :)

**Comment by gokarnm** [comment] 2017-03-15 20:03
@nosider, thanks for reporting this! Could you provide the stack trace for the case where `Microsoft.Extensions.DependencyModel.CompilationLibrary` throws `TypeInitializationException`?

**Comment by gokarnm** [comment] 2017-03-17 00:15
@nosider , which version of .NET Core are you using, could you share the project.json? I was able to access properties on `RuntimeEnvironment` without any issues. Here are the values I get.

```
RuntimeEnvironment.RuntimeArchitecture = x64
RuntimeEnvironment.OperatingSystem = amzn
RuntimeEnvironment.OperatingSystemPlatform = Linux
RuntimeEnvironment.OperatingSystemVersion = 2016.03
```

**Comment by nosider** [comment] 2017-03-17 03:23
@gokarnm , Great! I guess it is a problem on my end and hence it can be resolved.

Just to be sure I have just tried again, by running at app locally and in Docker and it was successful. Then I published it to Lambda, where it still fails unfortunately.

Below are the project.json contents (the references are hierarchical)

**Actual Lambda Project**
```
{
    "version": "1.0.0-*",
    "buildOptions": {
        "emitEntryPoint": true,
        "preserveCompilationContext": true
    },

    "dependencies": {
        "Microsoft.NETCore.App": {
            "version": "1.0.0",
            "type": "platform"
        },
        "AWSSDK.Extensions.NETCore.Setup": "3.3.0.2",
        "AWSSDK.S3": "3.3.5.2",
        "Amazon.Lambda.Core": "1.0.0",
        "Amazon.Lambda.AspNetCoreServer": "0.9.0-preview1",
        "Amazon.Lambda.Logging.AspNetCore": "1.0.0",
        "Amazon.Lambda.Serialization.Json": "1.0.1",
        "Amazon.Lambda.Tools": {
            "type": "build",
            "version": "1.2.1-preview1"
        },
        "JE.AspNetCore.Example": "1.0.0-*"
    },

    "tools": {
        "Amazon.Lambda.Tools": "1.2.1-preview1",
        "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final"
    },

    "frameworks": {
        "netcoreapp1.0": {
            "imports": "dnxcore50"
        }
    },

    "publishOptions": {
        "include": [
            "wwwroot",
            "**/*.cshtml",
            "appsettings.json"
        ]
    },

    "scripts": {
        "postpublish": [
            "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%"
        ]
    }
}
```

which in-turn references **JE.AspNetCore.Example**
```
{
    "version": "1.0.0-*",

    "dependencies": {
        "JE.NetCore.Asp": "1.0.0-*"
    },

    "frameworks": {
        "netcoreapp1.0": {
            "imports": "dnxcore50"
        }
    },
    "buildOptions": {
        "embed": "Views/**/*.cshtml"
    }
}
```

which in-turn references **JE.NetCore.Asp**
```
{
  "version": "1.0.0-*",

    "dependencies": {
        "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
        "Microsoft.AspNetCore.Server.Kestrel": "1.0.0",
        "Microsoft.AspNetCore.Mvc": "1.0.1",
        "Microsoft.AspNetCore.Routing": "1.0.1",
        "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
        "Microsoft.Extensions.Configuration.FileExtensions": "1.0.0",
        "Microsoft.Extensions.Configuration.Json": "1.0.0",
        "Microsoft.Extensions.Logging": "1.0.0",
        "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0",
        "JE.NetCore": "1.0.0-*",
        "Newtonsoft.Json": "9.0.1",
        "Microsoft.AspNetCore.Diagnostics": "1.1.0",
        "Microsoft.Extensions.FileProviders.Embedded": "1.1.0"
    },

    "frameworks": {
        "netcoreapp1.0": {
            "imports": "dnxcore50"
        }
    }
}
```

which in turn references **JE.NetCore**
```
{
  "version": "1.0.0-*",

    "dependencies": {
        "Autofac": "4.3.0",
        "Autofac.Extensions.DependencyInjection": "4.0.0",
        "Microsoft.DotNet.InternalAbstractions": "1.0.0",
        "Microsoft.Extensions.DependencyInjection": "1.0.0",
        "Microsoft.Extensions.DependencyModel": "1.1.0",
        "Microsoft.Extensions.PlatformAbstractions": "1.0.0",
        "System.Runtime.Loader": "4.3.0"
    },

    "frameworks": {
        "netcoreapp1.0": {
            "imports": "dnxcore50"
        }
    }
}
```


Here are the Logs to show the sequence of events:
```
02:51:35 START RequestId: a2a63416-0abc-11e7-885e-7b046a1ee364 Version: $LATEST
02:51:35 Incoming GET requests to /
02:51:35 [Information] Microsoft.AspNetCore.Hosting.Internal.WebHost: Request starting GET https://nj47fchh4i.execute-api.us-west-2.amazonaws.com/
02:51:35 [Debug] Microsoft.AspNetCore.Routing.Tree.TreeRouter: Request successfully matched the route with name '(null)' and template ''.
02:51:35 [Debug] Microsoft.AspNetCore.Mvc.Internal.ActionSelector: Action 'JE.AspNetCore.Example.Controllers.HomeController.WithQuestions (JE.AspNetCore.Example)' with id 'a07417df-ed55-4a84-acb9-6f6e2d50e3fe' did not match the constraint 'JE.NetCore.Asp.Constraints.QueryStringAttribute'
02:51:35 [Debug] Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker: Executing action JE.AspNetCore.Example.Controllers.HomeController.Index (JE.AspNetCore.Example)
02:51:35 [Information] Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker: Executing action method JE.AspNetCore.Example.Controllers.HomeController.Index (JE.AspNetCore.Example) with arguments ((null)) - ModelState is Valid
02:51:35 [Debug] Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker: Executed action method JE.AspNetCore.Example.Controllers.HomeController.Index (JE.AspNetCore.Example), returned result Microsoft.AspNetCore.Mvc.ViewResult.
02:51:35 [Debug] Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine: View lookup cache miss for view 'Index' in controller 'Home'.
02:51:35 Unknown error responding to request: TypeInitializationException: System.TypeInitializationException: The type initializer for 'Microsoft.Extensions.DependencyModel.CompilationLibrary' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Microsoft.DotNet.PlatformAbstractions.RuntimeEnvironment' threw an exception. ---> System.PlatformNotSupportedException: Operati
02:51:35 [Information] Microsoft.AspNetCore.Hosting.Internal.WebHost: Request finished in 80.8025ms 0
02:51:35 END RequestId: a2a63416-0abc-11e7-885e-7b046a1ee364
02:51:35 REPORT RequestId: a2a63416-0abc-11e7-885e-7b046a1ee364 Duration: 88.11 ms Billed Duration: 100 ms Memory Size: 256 MB Max Memory Used: 88 MB
```

**Comment by nosider** [comment] 2017-03-18 02:47
Found the issue that was causing the error. The error was caused by these two references:
`"Microsoft.AspNetCore.Diagnostics": "1.1.0"`
`"Microsoft.Extensions.FileProviders.Embedded": "1.1.0"`

Once I downgraded their version, the `TypeInitializationException` stopped happening.
`"Microsoft.AspNetCore.Diagnostics": "1.0.2"`
`"Microsoft.Extensions.FileProviders.Embedded": "1.0.1"`

Now that this part is working, the next hurdle is looking down on me - to see if it is possible to work around the reliance of `MetadataReferenceFeatureProvider` method `PopulateFeature` on the `Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths()` method that does not work in Lambda.

**Comment by genifycom** [comment] 2017-04-14 15:31
Yes, this is hugely annoying from Microsoft. They keep wanting to load the 1.1 version of libraries. We should be able to set .NET Core 1.0 in Nuget and only see compatible items. After all Microsoft introduced the concept of LTS support only for 1.0.

Anyone have any insight as to if the .NET Core 2.0 will be an LTS version? I sure hope so.

I have given Microsoft feedback about this, but of course no response. Amazon rocks in that regard.

**Comment by normj** [comment] 2017-12-12 08:57
Closing this in favor of issue https://github.com/aws/aws-lambda-dotnet/issues/149 which covers .NET Core 2.0 which is where Razor pages will work.

**Closed by normj** 2017-12-12 08:57 UTC
Labels: Question
