### ISSUE TITLE
LAMBDA_NET_SERIALIZER_DEBUG=true splits payloads over multiple lines

### ISSUE THREAD

**Issue by martincostello** [aws/aws-lambda-dotnet#1705] opened 2024-03-23 15:32 UTC
### Describe the bug

When `LAMBDA_NET_SERIALIZER_DEBUG=true` is set as an environment variable to try and debug JSON (de)serialization issues, if the JSON contains newlines it is split over multiple CloudWatch log messages, making it difficult to actually consume/understand the output.

### Expected Behavior

The JSON payload is contained in a single CloudWatch log entry.

### Current Behavior

The JSON payload is split across in multiple CloudWatch log entries.

### Reproduction Steps

Enable `LAMBDA_NET_SERIALIZER_DEBUG=true` and have a Lambda function process a JSON payload that contains new lines, for example:

```json
{
  "foo": "bar",
  "baz": "qux"
}
```

### Possible Solution

For `net6.0` and later, `string.ReplaceLineEndings()` could be used to transform the string before writing the payload to the console:

https://github.com/aws/aws-lambda-dotnet/blob/28cb636ec6c077ea7328d1d1a3d03cdb9a7e051b/Libraries/src/Amazon.Lambda.Serialization.SystemTextJson/AbstractLambdaJsonSerializer.cs#L60-L61

For example:

```diff
- var jsonDocument = debugReader.ReadToEnd();
+ var jsonDocument = debugReader.ReadToEnd().ReplaceLineEndings(string.Empty);
```

### AWS .NET SDK and/or Package version used

Amazon.Lambda.Serialization.SystemTextJson 2.4.1

### Targeted .NET Platform

.NET 8

### Operating System and version

Amazon Linux 2023

**Comment by ashishdhingra** [comment] 2024-03-25 16:41
@martincostello Good morning. Please let me know your kind of deployment, is it container based? Kindly refer to https://github.com/aws/aws-lambda-dotnet/issues/1265#issuecomment-1846471081, it might be related.

Thanks,
Ashish

**Comment by martincostello** [comment] 2024-03-25 16:44
No it is not a container, it is an Amazon Linux 2023 custom runtime, inside which there is a .NET 8 AoT application.

**Comment by ashishdhingra** [comment] 2024-03-25 17:46
Reproducible with project created using Visual Studio AWS custom runtime template and sending JSON payload. Deployed with `LAMBDA_NET_SERIALIZER_DEBUG` set to `true`. It logs JSON payload on separate lines, including any error stack trace:
```
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|   timestamp   |                                                                                                                                                        message                                                                                                                                                         |
|---------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 1711388585027 | INIT_START Runtime Version: provided:al2023.v14 Runtime Version ARN: arn:aws:lambda:us-east-2::runtime:03a38c888e1c30b5347fd6c19fbb4e795676bb49160eee95751fb66e988ce013                                                                                                                                                |
| 1711388585527 | START RequestId: 76f41555-1b70-47c4-8417-c4f69d75bddd Version: $LATEST                                                                                                                                                                                                                                                 |
| 1711388585857 | 2024-03-25T17:43:05.657Z 76f41555-1b70-47c4-8417-c4f69d75bddd info Lambda Deserialize System.String: {                                                                                                                                                                                                                 |
| 1711388585857 | "foo": "bar",                                                                                                                                                                                                                                                                                                          |
| 1711388585857 | "baz": "qux"                                                                                                                                                                                                                                                                                                           |
| 1711388585857 | }                                                                                                                                                                                                                                                                                                                      |
...                                                                                                                                                                                                               |
| 1711388586400 | END RequestId: 76f41555-1b70-47c4-8417-c4f69d75bddd                                                                                                                                                                                                                                                                    |
| 1711388586400 | REPORT RequestId: 76f41555-1b70-47c4-8417-c4f69d75bddd Duration: 871.14 ms Billed Duration: 1368 ms Memory Size: 256 MB Max Memory Used: 69 MB Init Duration: 496.78 ms                                                                                                                                                |
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

CCing @normj for any inputs.

**Comment by normj** [comment] 2024-03-25 21:53
This is a limitation of the `provided.alX` runtimes. Like containers the `provided.alX` custom runtimes don't have access to the telemetry API used by managed runtimes to send logs to Lambda as a discrete chunk and instead rely on scrapping stdout.

We hope to get .NET onboarded with Lambda's structured logging support soon. That would allow you to capture all of the log messages as a single line JSON and remove the issue of stdout line breaks causing issues.

**Comment by normj** [comment] 2024-03-29 21:04
I'm going to close this issue because Lambda has no plans for adding the telemetry API for the `provided.alX` runtimes. If you want to track the structured logging support follow this PR.
https://github.com/aws/aws-lambda-dotnet/pull/1588

**Closed by normj** 2024-03-29 21:04 UTC
Labels: bug, module/lambda-client-lib, needs-review, p2
