### ISSUE TITLE
APIGatewayCustomAuthorizerResponse does not contain UsageIdentifierKey

### ISSUE THREAD

**Issue by yngndrw-sage** [aws/aws-lambda-dotnet#273] opened 2018-05-14 13:44 UTC
The [custom authorizer response model](https://github.com/aws/aws-lambda-dotnet/blob/master/Libraries/src/Amazon.Lambda.APIGatewayEvents/APIGatewayCustomAuthorizerResponse.cs) does not a property for the [Usage Identifier Key](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-lambda-authorizer-output.html), used for usage plans.

**Comment by normj** [comment] 2018-05-23 05:41
Thanks for letting us know. I have checked in the fix to the dev branch and should go out with the next release. Let me know if the issue is blocking and if so I'll try and speed up the next release.

**Comment by yngndrw-sage** [comment] 2018-05-23 09:51
Thank you Norm, don't worry about speeding up the release as I've just subclassed it and added the missing property - I can change over to the correct implementation whenever it's released.

**Comment by normj** [comment] 2018-05-29 19:18
Version 1.1.3 was just released with this missing field.

**Closed by normj** 2018-05-29 19:18 UTC
Labels: Bug
