### ISSUE TITLE
ASP.NET serverless web app - ajax- 403 exception

### ISSUE THREAD

**Issue by pragatiulag** [aws/aws-lambda-dotnet#894] opened 2021-07-28 12:48 UTC
https://net-immersionday.workshop.aws/2-how-how-to-deploy-donet-apps/serverless/3-serverless-application.html

Followed the steps to create ASP.NET serverless web app and deployed using lambda.
In one of views we are trying to call controller action method(httppost) via ajax. 
But the web app is raising 403 forbidden exception.

Are we missing any configuration?

**Comment by ashishdhingra** [comment] 2021-07-28 18:54
Hi @pragatiulag,

Good morning.
 
Thanks for posting guidance question. Somehow, I'm unable to reproduce the issue.

- Followed steps in https://net-immersionday.workshop.aws/2-how-how-to-deploy-donet-apps/serverless/3-serverless-application.html to create Serverless Web app.
- Modified `Startup.cs` to below to add support of MVC:
```C#
public class Startup
{
    public Startup(IConfiguration configuration)
    {
        Configuration = configuration;
    }

    public IConfiguration Configuration { get; }

    // This method gets called by the runtime. Use this method to add services to the container.
    public void ConfigureServices(IServiceCollection services)
    {
        //services.AddRazorPages();
        services.AddMvc(a => a.EnableEndpointRouting = false);
    }

    // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
    public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
    {
        if (env.IsDevelopment())
        {
            app.UseDeveloperExceptionPage();
        }
        else
        {
            app.UseExceptionHandler("/Error");
            // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
            app.UseHsts();
        }

        //app.UseHttpsRedirection();
        app.UseStaticFiles();

        app.UseRouting();
        app.UseMvc(routes =>
        {
            routes.MapRoute(
                name: "default",
                template: "{controller=Home}/{action=Index}/{id?}");
        });
        app.UseAuthorization();
    }
}
```
- Created a new controller `HomeController` with the following minimal code:
```C#
using Microsoft.AspNetCore.Mvc;

namespace AWSServerlessAJAX_Issue894.Controllers
{
    public class HomeController : Controller
    {
        // GET: HomeController
        public ActionResult Index()
        {
            return View();
        }

        // GET: HomeController/Details/5
        public string Details(int id)
        {
            return $"ID: {id}";
        }

        

        [HttpPost]
        public string Edit(int id)
        {
            return $"Updated ID: {id}";
        }
    }
}
```
- Added the view `Index.cshtml` for action method `Index`:
```CSHTML
<script type="text/javascript"
        src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js">
</script>
<script type="text/javascript" language="javascript">
    $(document).ready(function () {
        $("#driver").click(function (event) {
            $.ajax({
                url: '@Url.Action("Edit","Home", new { id = 5 })',
                data: {
                    format: 'json'
                },
                error: function () {
                    $('#info').html('<p>An error has occurred</p>');
                },
                success: function (data) {
                    $('#stage').html(data);
                },
                type: 'POST'
            });
            
        });
    });
</script>
<div id="stage" style="background-color:cc0;">
    STAGE
</div>
<div id="info">
    STAGE
</div>
<input type="button" id="driver" value="Load Data" />
```
- Tested the changes locally by navigating to https://localhost:44341/Home (your post might be different) and clicking on Load Data button which fires the `POST` AJAX call to `Edit` action method. It successfully loads the data.
- Deployed changes to AWS Lambda. It generated URL something like https://lvttr00v29.execute-api.us-east-2.amazonaws.com/Prod.
- Tested the page https://lvttr00v29.execute-api.us-east-2.amazonaws.com/Prod/Home. It works fine.

(Kindly note that above code is for reproduction purposes only and does not follow any coding guidelines.)

May be if you could provide the minimal reproducible sample code solution, I can try to troubleshoot the issue.

Thanks,
Ashish

**Comment by pragatiulag** [comment] 2021-07-29 08:55
Hi @ashishdhingra

Thank you for the detailed help. On comparing the ajax call in your code with ours we found the issue:

In our .js file we had  url: "/MySkills/AddUpdateSkills", in ajax call. This works in localhost but not in code deployed to lambda.

On changing this to url: '@Url.Action("AddUpdateSkills", "MySkills")', the 403 issue in lambda deployed code is resolved.

But to use  url: '@Url.Action("AddUpdateSkills", "MySkills") we cannot have the JS code in separate .js file. We want to keep JS code in JS files. Any suggestion?

Below code in .js file was not working:

```
 $.ajax({
        type: "POST",
        url: "/MySkills/AddUpdateSkills",
        data: { SkillDetails: SkillDetails },
        dataType: "json",
        success: function (r) {
            $('#SkillsAddSuccessModel').modal('show');
        }
    });
```

This script when placed in View is working:

    ```
    $.ajax({
            url: '@Url.Action("AddUpdateSkills", "MySkills")',
            type: 'POST',
            data: { SkillDetails: SkillDetails },
            async: true,
            success: function (data) {
                $('#SkillsAddSuccessModel').modal('show');
            },
            error: function (xhr, status) {
            },
        });``
```

**Comment by ashishdhingra** [comment] 2021-07-29 16:15
@pragatiulag You could create a JavaScript function, something like below:
```JavaScript
function addUpdateSkill(postUrl)
{
    if(postUrl != undefined && postUrl != null) {
        $.ajax({
            type: "POST",
            url: "/MySkills/AddUpdateSkills",
            data: { SkillDetails: SkillDetails },
            dataType: "json",
            success: function (r) {
                $('#SkillsAddSuccessModel').modal('show');
            }
        }
    });
} 
```
and then invoke this function from your view file attached to an event handler (such as button click), something like:
```CSHTML
    addUpdateSkill(@Url.Action("AddUpdateSkills", "MySkills"));
```

The better approach to organize JavaScript code is to use modules into each category (refer https://www.freecodecamp.org/news/javascript-modules-a-beginner-s-guide-783f7d7a5fcc/ for guidance). For instance, in this case, you could define `Skills` JavaScript module.

So modified version would look something like below:
```JavaScript
var Skills = (function () {
    
  return {
    addUpdate: function(postUrl) {
          if(postUrl != undefined && postUrl != null) {
            $.ajax({
                type: "POST",
                url: "/MySkills/AddUpdateSkills",
                data: { SkillDetails: SkillDetails },
                dataType: "json",
                success: function (r) {
                    $('#SkillsAddSuccessModel').modal('show');
                }
            }
        });
    }
  }
})();
```
and invoke it like below:
```
Skills.addUpdate(@Url.Action("AddUpdateSkills", "MySkills"));
```

Hope this helps. Kindly use the above code as guidance, you may want to implement better design patterns and test your code in non-production environment.

Closing this issue since the original issue with Serverless app is resolved.

Thanks,
Ashish

**Closed by ashishdhingra** 2021-07-29 16:15 UTC
Labels: guidance, module/aspnetcore-support, response-requested
