### ISSUE TITLE
AWS LEX V2 lambda event serialize issue

### ISSUE THREAD

**Issue by antonysamy931** [aws/aws-lambda-dotnet#1248] opened 2022-07-19 13:46 UTC
### Describe the bug

Not able to deserialize event object in lambda handler. It throws following error
`tions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
 `
**Request object :**
`
{
    "sessionId": "042444039656365",
    "inputTranscript": "hi",
    "interpretations": [
        {
            "intent": {
                "slots": {},
                "confirmationState": "None",
                "name": "Welcome_Intent",
                "state": "InProgress"
            },
            "nluConfidence": 1
        },
        {
            "intent": {
                "slots": {},
                "confirmationState": "None",
                "name": "FallbackIntent",
                "state": "InProgress"
            }
        }
    ],
    "responseContentType": "text/plain; charset=utf-8",
    "invocationSource": "DialogCodeHook",
    "messageVersion": "1.0",
    "transcriptions": [
        {
            "resolvedContext": {
                "intent": "Welcome_Intent"
            },
            "transcription": "hi",
            "resolvedSlots": {},
            "transcriptionConfidence": 1
        }
    ],
    "sessionState": {
        "originatingRequestId": "f2837226-8607-4ae5-b62b-db506533871e",
        "intent": {
            "slots": {},
            "confirmationState": "None",
            "name": "Welcome_Intent",
            "state": "InProgress"
        }
    },
    "inputMode": "Text",
    "bot": {
        "aliasName": "TestBotAlias",
        "aliasId": "TSTALIASID",
        "name": "DP_botv2_research",
        "version": "DRAFT",
        "localeId": "en_US",
        "id": "HMKPH2BKSM"
    }
}
`

### Expected Behavior

LexV2Event object should be populated based on the request object.

### Current Behavior

Throws de-serialization errors.

### Reproduction Steps

1. Create Lex v2 bot
2. Create intent
3. Test

### Additional Information/Context

**Error place**
![image](https://user-images.githubusercontent.com/5698116/179765029-8a3392ea-af10-4611-a3b3-2466fa854c38.png)

`nluConfidence` is class type. In the request json `nluConfidence` is value type(integer).
![image](https://user-images.githubusercontent.com/5698116/179765756-6299ec1d-c056-47d6-bf1b-a2de46d12ef0.png)

### AWS .NET SDK and/or Package version used

Amazon.Lambda.Core : 2.1.0
Amazon.Lambda.LexV2Events : 1.0.0
Amazon.Lambda.Serialization.SystemTextJson : 2.3.0

### Targeted .NET Platform

.Net 6

### Operating System and version

windows 10

**Comment by antonysamy931** [comment] 2022-07-19 13:51
Request & response documentation for lex v2
https://docs.aws.amazon.com/lexv2/latest/dg/lambda.html#lambda-input-format

**Comment by ashishdhingra** [comment] 2022-07-19 16:17
Hi @antonysamy931,

Good morning.

Thanks for reporting the issue. The LexV2 event classes have been modeled as per the documentation. If you refer API reference for [Interpretation](https://docs.aws.amazon.com/lexv2/latest/dg/API_runtime_Interpretation.html) and [ConfidenceScore](https://docs.aws.amazon.com/lexv2/latest/dg/API_runtime_ConfidenceScore.html) types, the `nluConfidence` is a [ConfidenceScore](https://docs.aws.amazon.com/lexv2/latest/dg/API_runtime_ConfidenceScore.html) with the `score` value of type `Double`. The documentation link [LexV2: Input event format](https://docs.aws.amazon.com/lexv2/latest/dg/lambda.html#lambda-input-format) also models this as:
```JSON
"nluConfidence": {
                "score": number
            }
```

Please advise on how did you test end-to-end integration.

Thanks,
Ashish

**Comment by antonysamy931** [comment] 2022-07-21 15:05
Hi @ashishdhingra , 

I have created bot using lex version 2. 
Created c# lambda and map to lex fulfillment. 
Invoke request from lex to lambda, it throws parsing error.

**Comment by ashishdhingra** [comment] 2022-08-01 22:07
Reproducible. Need to check with service team on this change since the `Amazon.Lambda.LexV2Events` followed the documentation and the scenario was tested successfully earlier.

**Comment by ashishdhingra** [comment] 2022-08-01 22:27
P69014723

**Comment by ashishdhingra** [comment] 2022-08-02 16:56
Per service team, `nluConfidence` in case of Lambda input event is a `double`. They will get the documentation corrected. We would work to fix this in `Amazon.Lambda.LexV2Events` package.

**Comment by ashishdhingra** [comment] 2022-08-03 05:11
This has been fixed in [Amazon.Lambda.LexV2Events 1.0.1](https://www.nuget.org/packages/Amazon.Lambda.LexV2Events/1.0.1)

**Closed by ashishdhingra** 2022-08-03 05:11 UTC
Labels: bug, service-api, module/lambda-client-lib, A, queued
