### ISSUE TITLE
Using Google.Apis.Auth results in a exception

### ISSUE THREAD

**Issue by stevecookms** [aws/aws-lambda-dotnet#576] opened 2020-01-31 16:39 UTC
System.IO.FileLoadException: Could not load file or assembly 'Google.Apis.Auth, Version=1.43.0.0, Culture=neutral, PublicKeyToken=4b01fa6e34db77ab'. An operation is not legal in the current state. (Exception from HRESULT: 0x80131509)
   at Drivetrain.Function.FunctionHandler(ILambdaContext context)

This works when I publish to Lambda, but I cannot debug the function.

**Comment by normj** [comment] 2020-01-31 18:29
Could you share a small sample project that reproduces the error?

**Comment by stevecookms** [comment] 2020-01-31 19:02
Sure!

It is basic out of the box Lambda using the templates installed into VS2019.  I only added 1 nuget dependency.  You have to use the dependency in order to cause the exception.

[AWSLambda1.zip](https://github.com/aws/aws-lambda-dotnet/files/4140906/AWSLambda1.zip)

**Comment by klaytaybai** [comment] 2020-02-03 23:22
Thanks for the feedback and sample app.  I'm going to close this issue as a duplicate of https://github.com/aws/aws-lambda-dotnet/issues/419.  Please consider following and joining the discussion there.

**Closed** 2020-02-03 23:23 UTC
Labels: duplicate, investigating
