### ISSUE TITLE
Need to create aws lambda layer from class library project which referenced local DLL's

### ISSUE THREAD

**Issue by suryasinghRateGain** [aws/aws-lambda-dotnet#776] opened 2020-12-11 11:47 UTC

**Comment by ashishdhingra** [comment] 2020-12-11 17:17
Hi @suryasinghRateGain,

Good morning.

Following references could be helpful for developing with AWS Lambda Layers:
- [AWS Lambda layers with .NET Core](https://aws.amazon.com/blogs/developer/aws-lambda-layers-with-net-core/)
- [Creating AWS Lambda Layers in ASP.NET Core - Getting started](https://referbruv.com/blog/posts/creating-aws-lambda-layers-in-aspnet-core-getting-started)
- [Layers for .NET Core Lambda Functions](https://github.com/aws/aws-extensions-for-dotnet-cli/blob/master/docs/Layers.md)

_**NOTE:** The code in the articles should be used as a reference. AWS Support team is not responsible for any data loss. All the code should be tested properly before deploying to production._

Hope this helps. In case any additional input is required, kindly share more details in the following format:



## Expected Behavior



## Current Behavior






## Possible Solution



## Steps to Reproduce (for bugs)





## Context



## Your Environment

* AWSSDK.Core version used: 
* Service assembly and version used: 
* Operating System and version: 
* Visual Studio version: 
* Targeted .NET platform: 

## .NET Core Info

* .NET Core version used for development: 
* .NET Core version installed in the environment where application runs: 
* Output of `dotnet --info`: 
* Contents of project.json/project.csproj: 

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html 


Thanks,
Ashish

**Comment by suryasinghRateGain** [comment] 2020-12-13 11:28
I have already follow these approach it works for simple layer(which do not include local dll's files) but issue is it does not upload local dll's file which referenced class library project while converting to  aws lambda layer

**Comment by ashishdhingra** [comment] 2020-12-14 18:55
Hi @suryasinghRateGain,

Request you to provide the information in above format. Also share the sample solution which I could use to reproduce the issue. I will give it a try at my end.

Thanks,
Ashish

**Comment by suryasinghRateGain** [comment] 2020-12-15 06:38
<img width="897" alt="issue" src="https://user-images.githubusercontent.com/72724894/102179978-1adfed00-3ece-11eb-8962-1393634679b6.png">

this dll get load and work when I deploy on lambda function but not able to upload on aws lambda layer so that it can be used   as common code

**Comment by ashishdhingra** [comment] 2020-12-15 20:24
Hi @suryasinghRateGain,

Please refer the https://github.com/aws/aws-lambda-dotnet/issues/599#issuecomment-598486351. The Lambda layer feature is dependent on .NET runtime package store feature (more information at [Runtime package store](https://docs.microsoft.com/en-us/dotnet/core/deploying/runtime-store)).

I tried reproducing scenario with the following `.csproj` file:
```XML
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Mono.Cecil">
      <HintPath>..\Binaries\nunit.engine\Mono.Cecil.dll</HintPath>
    </Reference>
    <Reference Include="nunit.engine">
      <HintPath>..\Binaries\nunit.engine\nunit.engine.dll</HintPath>
    </Reference>
    <Reference Include="nunit.engine.api">
      <HintPath>..\Binaries\nunit.engine\nunit.engine.api.dll</HintPath>
    </Reference>
    <Reference Include="nunit.engine.core">
      <HintPath>..\Binaries\nunit.engine\nunit.engine.core.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
```

Thereafter, I used the below command to create .NET runtime package store:
```
dotnet store --manifest DllLayer.csproj --runtime linux-x64 --framework netcoreapp3.1 --framework-version 3.1.0 --output bin/dotnetcore/store --skip-optimization
```

It generated the below `artifact.xml`:
```XML
<StoreArtifacts>
  <Package Id="Newtonsoft.Json" Version="12.0.3" />
</StoreArtifacts>
```

Notice that the `artifact.xml` only contains dependencies for NuGet package, there is no dependency on the referenced DLLs. Looks like .NET runtime package store only works with NuGet packages.

Hence, this appears to be the limitation of .NET runtime package store.

I'm not sure how you could manually create the packages in a separate folder and then just add that folder to your list of NuGet sources when creating the layer, this is something you would need to explore.

Hope this provides some useful information. Closing this issue.

Thanks,
Ashish

**Closed by ashishdhingra** 2020-12-15 20:24 UTC
Labels: guidance, module/custom-runtime, response-requested
