### ISSUE TITLE
Running deploy-function using a profile that assumes a role using MFA doesn't work

### ISSUE THREAD

**Issue by mrbennett** [aws/aws-lambda-dotnet#155] opened 2017-08-31 23:41 UTC
Hi there,

The way we control access involves assuming roles from a base identity account into other ones with MFA. Given a brand new empty function created using `dotnet new lamdba.EmptyFunction` and a profile looks something like:

```
[profile profile-that-assumes-role-with-mfa]
role_arn = *valid role arn*
mfa_serial = *valid mfa serial*
source_profile = *base identity in credentials file*
region = ap-southeast-2
```

When I run:

```
dotnet lambda deploy-function test-mfa --profile profile-that-assumes-role-with-mfa
```

I get an error saying:

```
Error retrieving configuration for function test-mfa: Assembly AWSSDK.SecurityToken could not be found or loaded. This assembly must be available at runtime to use Amazon.Runtime.AssumeRoleAWSCredentials.
```

Is this supported / supposed to work?

**Comment by normj** [comment] 2017-08-31 23:53
We do need to include AWSSDK.SecurityToken in our list of dependencies for the lambda tooling which will fix the missing dependency issue. I marked it as enhancement though because we don't have support in the Lambda tooling to prompt for the MFA token which looks like will be blocker if I fix the issue about the missing dependency.

**Comment by ashishdhingra** [comment] 2021-08-09 23:53
Hi @mrbennett,

Good afternoon.

I as going through backlog and came across this issue. Looks like this is addressed, refer https://github.com/aws/aws-extensions-for-dotnet-cli/blob/master/src/Amazon.Common.DotNetCli.Tools/Amazon.Common.DotNetCli.Tools.csproj where it includes dependency to `AWSSDK.SecurityToken`. Please confirm if the issue is resolved for you and should we close this issue.

Thanks,
Ashish

**Comment by mrbennett** [comment] 2021-08-18 11:41
Hi @ashishdhingra,

Sorry for the late reply: I no longer have the means to test this since have moved jobs and the setup isn't that way anymore. If you like you can just close the issue.

**Closed** 2021-08-18 14:02 UTC
Labels: closing-soon, feature-request, response-requested, module/lambda-client-lib
