### ISSUE TITLE
Unable to run .NET Core 3.1 application that includes reference to Entity Framework

### ISSUE THREAD

**Issue by jchadwick** [aws/aws-lambda-dotnet#710] opened 2020-07-27 03:31 UTC
## Description
After simply adding a reference to the `Microsoft.EntityFrameworkCore` package, requests to the application fail with the following error:

```
System.MissingMethodException: Method not found: 'Microsoft.Extensions.Hosting.IHostBuilder Microsoft.Extensions.Hosting.HostingHostBuilderExtensions.ConfigureServices(Microsoft.Extensions.Hosting.IHostBuilder, System.Action`1<Microsoft.Extensions.DependencyInjection.IServiceCollection>)'.
   at Amazon.Lambda.AspNetCoreServer.AbstractAspNetCoreFunction`2.Start()
   at Amazon.Lambda.AspNetCoreServer.AbstractAspNetCoreFunction`2..ctor(StartupMode startupMode)
   at Amazon.Lambda.AspNetCoreServer.AbstractAspNetCoreFunction`2..ctor()
   at Amazon.Lambda.AspNetCoreServer.APIGatewayProxyFunction..ctor()
   at LambdaIssue.LambdaEntryPoint..ctor()
```

## Reproduction Steps
(See [this repo](https://github.com/jchadwick/aws-lambda-dotnet-issue) for a runnable example -- just run the Mock tool and execute the `GET` request)
1. Create new AWS Serverless application using project template
2. Add reference to the `Microsoft.EntityFrameworkCore` package
3. Run the application in the Mock test tool and execute a GET request

### Logs
N/A - just that call stack above

### Environment
* Build Version: Have been able to duplicate with all versions 5.0.0+
* OS Info: Windows 10
* Build Environment: Visual Studio
* Targeted .NET Platform:  .NET Core 3.1

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment] 2020-07-27 21:11
Hi @jchadwick,

Thanks for reporting the issue. 

I tried to follow the steps that were shared in the issue to create a new Serverless application using project template. Everything appears to be working fine. Here are the environment details:

**OS Info:** Windows 10
**IDE:** Visual Studio 2019 version 16.6.4
**Target Platform:** .NET Core 3.1
**AWS Tools and SDK:** 3.3.780

Please let me know if you are able to recreate the issue when creating altogether new application from scratch.

Thanks,
Ashish

**Comment by jchadwick** [comment] 2020-07-28 13:18
@ashishdhingra thanks for looking into this!
Are you saying that my demo repo works fine for you?

**Comment by ashishdhingra** [comment] 2020-07-28 16:09
Hi @jchadwick,

Just to make sure that we have a clean application state, I had created a fresh Serverless application from scratch using Visual Studio AWS project template targeting .NET Core and it works fine after adding Microsoft.EntityFrameworkCore package. I didn't tried to reproduce the issue using your repo, but would have a look at it. 

Please let me know if you had migrated your application from .NET Core 2.0 to 3.1 (just to eliminate that scenario).

Thanks,
Ashish

**Comment by normj** [comment] 2020-07-28 21:54
I was able to reproduce the problem in the .NET Mock Lambda Test Tool. I'll assign the issue to myself to take a deeper look.

**Comment by loe-lobo** [comment] 2020-09-24 08:23
Hi @normj, do you have any updates about this issue? We are trying to use the .Net Mock Lambda Test tool to test a .net Core 3.1 API, and we are facing the same error. 

Thanks,
Loe

**Comment by plittlewood-rpt** [comment] 2020-10-01 13:18
Hi @normj, I've run into this same issue today. Same error message and using entity framework in my project

Cheers
Pete

**Comment by stagha** [comment] 2020-10-07 22:13
Looks very similar to [this issue](https://github.com/aws/aws-lambda-dotnet/issues/668). Same error, different library.

If I'm not wrong, I created a simple [test project](https://github.com/stagha/netcoreapp3.1-lambda-with-microsoft.net-dependency) to help diagnose.

I'm very interested in a solution. We are stuck on .NET Core 2.1 because of not being able to develop with the test tool on 3.1.

**Comment by ashishdhingra** [comment] 2020-10-22 23:16
Issue similar to #668

**Comment by dr3x** [comment] 2020-12-29 22:34
Same issue, using [Microsoft.EntityFrameworkCore 3.1.10](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore/3.1.10?_src=template)

`System.MissingMethodException: Method not found: 'Microsoft.Extensions.Hosting.IHostBuilder Microsoft.Extensions.Hosting.HostingHostBuilderExtensions.ConfigureServices(Microsoft.Extensions.Hosting.IHostBuilder, System.Action`1<Microsoft.Extensions.DependencyInjection.IServiceCollection>)'.
   at Amazon.Lambda.AspNetCoreServer.AbstractAspNetCoreFunction`2.Start()
   at Amazon.Lambda.AspNetCoreServer.AbstractAspNetCoreFunction`2..ctor(StartupMode startupMode)
   at Amazon.Lambda.AspNetCoreServer.AbstractAspNetCoreFunction`2..ctor()
   at Amazon.Lambda.AspNetCoreServer.APIGatewayHttpApiV2ProxyFunction..ctor()at...`

**Comment by soccerboymalloy-patriot** [comment] 2021-03-10 01:37
I was getting the same `Microsoft.Extensions.Hosting.IHostBuilder` error as above when using version 3 of the tool. I resolved that specific issue by upgrading to version 5 with a .Net 5 Container Lambda, but now I'm stuck on a new error:
```
System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<!!0> System.Net.Http.Json.HttpContentJsonExtensions.ReadFromJsonAsync(System.Net.Http.HttpContent, System.Text.Json.JsonSerializerOptions, System.Threading.CancellationToken)'.
   <... custom code ...>
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   <... custom code ...>
   at Amazon.Lambda.TestTool.Runtime.LambdaExecutor.ProcessReturnAsync(ExecutionRequest request, Object lambdaReturnObject) in C:\codebuild\tmp\output\src598299731\src\Tools\LambdaTestTool\src\Amazon.Lambda.TestTool\Runtime\LambdaExecutor.cs:line 138
   at Amazon.Lambda.TestTool.Runtime.LambdaExecutor.ExecuteAsync(ExecutionRequest request) in C:\codebuild\tmp\output\src598299731\src\Tools\LambdaTestTool\src\Amazon.Lambda.TestTool\Runtime\LambdaExecutor.cs:line 62
```

Being unable to use the testing tool is blocking adoption of Lambdas for my organization. Any update on this?

Can we consolidate this bug into either this ticket or the related one (https://github.com/aws/aws-lambda-dotnet/issues/668)?

**Comment by ashishdhingra** [comment] 2021-04-12 20:32
This should be fixed in as part of commit https://github.com/aws/aws-lambda-dotnet/commit/adc0687af7174d1d03183a6a8dd7d90484944920, in version 0.11.3 of Lambda Test Tool.

**Closed by ashishdhingra** 2021-04-12 20:32 UTC
Labels: B, bug, investigating, module/lambda-test-tool
