### ISSUE TITLE
'dotnet lambda package' without a razor view strips off dependencies

### ISSUE THREAD

**Issue by jcastrocalvo** [aws/aws-lambda-dotnet#219] opened 2018-01-31 20:30 UTC
When utilizing a aspnetcore project that does not serve or include any Razor views, dependencies for platforms outside of linux get stripped off.  A concrete example of this would be an aspnetcore based API.

Specifically, adding the following argument strips out dependencies that are needed on other platforms outside of linux:

`arguments.Append(" -r linux-x64 --self-contained false /p:PreserveCompilationContext=false");`

this is due to the check for this argument, it is a search for a Razor view:

`Directory.GetFiles(fullProjectLocation, "*.cshtml", SearchOption.AllDirectories).Length == 0`

However, in the case that I am proposing, a project with no Razor views that is used in other platforms fails to start due to missing platform dependencies. 

The specific statement is located here:
[https://github.com/aws/aws-lambda-dotnet/commit/3a63d15bb15778fec6665049d121ba1a60c183f1#diff-6a82055c9d25a2c4588514221789a351](url)

The current workout that I have been using is creating a dummy .cshtml file to avoid that branch of logic.

**Comment by normj** [comment] 2018-01-31 20:34
Can you explain the use case of using the Lambda packaging and deployment tools for other platforms besides Lambda? Including all of the Windows and Mac dependencies in a Lambda package bundle can greatly increase the size of the bundle.

**Comment by jcastrocalvo** [comment] 2018-01-31 23:20
In our scenario we utilize the lambda package as a form of distribution of an api to other developer’s machines so they do not have to worry about the build process.  But in order to do this, we need the other runtimes.  Doing a `dotnet publish` and a `dotnet lambda package` would cover both of our cases. But it would be nice to use the same package that `dotnet lambda package` outputs for both of these cases.  A flag option would be very useful so we could specify additional runtimes in case it is necessary. Maybe even leaving the current specification as default but also having the option to do an override?

**Comment by andycmaj** [comment] 2018-02-02 04:36
dupe of #206?

**Comment by jcastrocalvo** [comment] 2018-02-07 22:32
@andycmaj sort of a duplicate. I would prefer to specify from the command line argument but I could settle for a project configuration.  Eventually both options could also be added.  I would be fine doing a pull request for either fix.  If you would like, I can start on your pull request first.

**Closed** 2018-02-08 19:13 UTC
Labels: Question
