### ISSUE TITLE
Dead Letter Queue configuration

### ISSUE THREAD

**Issue by bjorg** [aws/aws-lambda-dotnet#123] opened 2017-05-25 20:07 UTC
I've encountered a couple of odd issues when configuring the DLQ.

1) If I configure the DLQ setting on the lambda function using the AWS console, then every time I deploy a new function using `dotnet lambda deploy-function` it resets my DLQ configuration to nothing. This is quite different from environment variables, which are not touched when a function is redeployed.

2) I can specify the DQL ARN on the command line using `-dlta` or `--dead-letter-target-arn` and that works as expected. However, I cannot predefine the value in the `aws-lambda-tools-defaults.json` file. Adding a `"dead-letter-target-arn"` seems to have no effect. So I have to remember to always specify it on the command line, which is not reliable.

Fixing either issue would be a great help! There's nothing worse than believing that you've built a reliable serverless app just to discover that the necessary DLQ settings were unintentionally removed by redeploying the lambda function!

**Comment by bjorg** [comment] 2017-05-25 20:11
As a side note, if I had instructions in how to build and use a local version of the `aws-lambda-dotnet` tooling, I could look into fixing this issue myself and provide a pull request. I think that the first issue (deleting existing DLQ settings) is definitively a bug.

**Comment by normj** [comment] 2017-05-25 23:52
Thanks for letting us know about the issue with DLQ. I have just committed a fix that will go out in the next release which I'll try and get out soon. https://github.com/aws/aws-lambda-dotnet/commit/05b1264ff56344e69caa12abb9364e033d480195

It was done by design when redeploying a function to not pull function configuration information from `aws-lambda-tools-defaults.json` because I only wanted the function configuration to change if it was being done explicitly.

**Comment by bjorg** [comment] 2017-05-26 19:04
I usually install the tools using `dotnet new -i Amazon.Lambda.Templates::*`, which I found on one of the original blog posts when it was announced. Although, I can't find any documentation on that `-i` switch!

Anyway, how will I know there's a new version ready to install?

**Comment by normj** [comment] 2017-06-01 06:47
Version 1.6.0 of Amazon.Lambda.Tools was released with this fix. Also version 1.3.0 of Amazon.Lambda.Templates was released with updated blueprints referencing this new version. 

I have seen in the .NET Core 2.0 preview build that they documented the `-i` switch.

I keep the [RELEASE.CHANGELOG.md](https://github.com/aws/aws-lambda-dotnet/blob/master/RELEASE.CHANGELOG.md) updated when I release new versions. I'm open to suggestions for better ways to message new releases.

**Comment by bjorg** [comment] 2017-06-01 17:09
That's great! Now that I know, I can track changes to that file.

I can confirm that running 'dotnet lambda deploy-function` does not erase the DLQ setting anymore. 
However, I do have the `"dead-letter-target-arn" key set in my `aws-lambda-tools-defaults.json` file. Is that used or ignored?

**Comment by normj** [comment] 2017-06-01 17:16
You have the `dead-letter-target-arn` set and it is being ignored when you are creating a **new** function?

**Comment by bjorg** [comment] 2017-06-01 17:37
Sorry, I wasn't clear, so I did some testing.

1) Creating a new lambda function sets the DLQ when the `dead-letter-target-arn` key is set in `aws-lambda-tools-defaults.json`.

2) Updating a lambda function does NOT set the DLQ even if it is set in `aws-lambda-tools-defaults.json`.

3) Updating a lambda function with `dead-letter-target-arn` set to `""` does not clear the DLQ setting (which is consistent with point 2).

I think it boils down to what the purpose of `aws-lambda-tools-defaults.json` is. We use it to capture how to publish and update our lambda functions with all their settings. However, it seems to be primarily geared towards first time creation, is that correct?

So for us, a further improvement would be to remove the account and region information for the `function-role` and `dead-letter-target-arn` keys to make it easier to publish on different accounts, but I suspect that's out of scope.

**Comment by bjorg** [comment] 2017-06-01 17:47
BTW, here's an easy way to monitor the release notes! :)
https://github.com/aws/aws-lambda-dotnet/commits/master/RELEASE.CHANGELOG.md.atom

**Comment by normj** [comment] 2017-06-02 05:01
When you update a function the information about which function to update (profile, region, function-name) and the information on how to build the project (framework and configuration) is used. But when updating a function the tooling doesn't use the function configuration fields. The reason I did it that way is I was afraid of people deploying a function, then make change to the function's configuration in the console or toolkit like changing the environment variable for a database connection string. They probably wouldn't realize the next time they update the function it would revert those changes.

Maybe what we need is another switch which would force a sync of the `aws-lambda-tools-default.json` function configurations fields. That way I know they opted into the behavior of having the function configuration values be overwritten.

For example something like this:
```
dotnet lambda deploy-function --force-config-update
```

**Comment by bjorg** [comment] 2017-06-05 16:01
I think it comes down to what your goals are with `aws-lambda-tools-default.json`. If it's a getting started quick tool and if it's part of a development lifecycle.

Either way, this particular issue is resolved and can be closed. Thank you very much for the quick turn around!

**Closed** 2017-06-06 20:02 UTC
Labels: Bug
