### ISSUE TITLE
"BlueprintBaseName" appears in generated Readme.md for new serverless.EmptyServerless

### ISSUE THREAD

**Issue by hakanson** [aws/aws-lambda-dotnet#906] opened 2021-08-25 19:29 UTC
## Description

Generated `Readme.md` has incorrect values under "Deploy application" where "BlueprintBaseName" appears when expecting "EmptyServerless"

> Execute unit tests
> 
>     cd "EmptyServerless/test/EmptyServerless.Tests"
>     dotnet test
> 
> Deploy application
> 
>     cd "BlueprintBaseName/src/BlueprintBaseName"
>     dotnet lambda deploy-serverless

## Reproduction Steps

`dotnet new serverless.EmptyServerless -n EmptyServerless`

look at output of `EmptyServerless/src/Readme.md`

### Logs
n/a

### Environment

* Build Version: 5.4.0
* OS Info: OSX 11.5.2
* Build Environment: Terminal `dotnet`
* Targeted .NET Platform:  dotnet core 3.1

## Resolution
- [ ] :wave: I can/would-like-to implement a fix for this problem myself

This is probably a result of the `BlueprintBaseName` string instead of `BlueprintBaseName.1` being used like in "Execute unit tests" section.

https://github.com/aws/aws-lambda-dotnet/blob/087590ce99274e16e26d37e1dfd73b0b71d1230a/Blueprints/BlueprintDefinitions/netcore3.1/EmptyServerless/template/src/BlueprintBaseName.1/Readme.md#L32-L42

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment] 2021-09-29 04:00
The issue is fixed in latest blueprint templates which could be installed using command `dotnet new -i "Amazon.Lambda.Templates::*"`.

**Closed by ashishdhingra** 2021-09-29 04:00 UTC
Labels: bug, module/aspnetcore-support, A, queued, low-effort
