### ISSUE TITLE
How to create we version of voice enabled AWS bot using c#

### ISSUE THREAD

**Issue by NeetaA** [aws/aws-lambda-dotnet#165] opened 2017-09-15 06:47 UTC
I want to create web version of audio chat bot using AWS polly in Dot net/C# .

Could you please help me?

**Comment by normj** [comment] 2017-10-16 17:58
Closing as this is a duplicate of https://github.com/aws/aws-lambda-dotnet/issues/166

**Closed by normj** 2017-10-16 17:58 UTC
