### ISSUE TITLE
The JSON value could not be converted to Amazon.CodePipeline.ArtifactLocationType

### ISSUE THREAD

**Issue by ingun37** [aws/aws-lambda-dotnet#768] opened 2020-12-01 08:03 UTC
## Description
DefaultLambdaJsonSerializer fails to decode payload coming from CodePipeline, specifically 
`$['CodePipeline.job'].data.inputArtifacts[0].location.type`
to
`Amazon.CodePipeline.ArtifactLocationType`

## Reproduction Steps
Define Lambda handler with type of Codepipeline payload
```c#
    public class CodePipelineEvent
    {
        [JsonPropertyName("CodePipeline.job")]
        public Amazon.CodePipeline.Model.Job job { get; set; }
    }
    public Task FunctionHandler(CodePipelineInput input, ILambdaContext context) { ... }
```
then test with an actual payload.

### Logs
```
Error converting the Lambda event JSON payload to type BenchmarkingLoader.CodePipelineInput: The JSON value could not be converted to Amazon.CodePipeline.ArtifactLocationType. Path: $['CodePipeline.job'].data.inputArtifacts[0].location.type | LineNumber: 0 | BytePositionInLine: 258.: JsonSerializerException
   at Amazon.Lambda.Serialization.SystemTextJson.DefaultLambdaJsonSerializer.Deserialize[T](Stream requestStream)
   at lambda_method(Closure , Stream , Stream , LambdaContextInternal )

   at System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(Type propertyType)
   at System.Text.Json.JsonPropertyInfoNotNullable`4.OnRead(ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonPropertyInfo.Read(JsonTokenType tokenType, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   at System.Text.Json.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.ParseCore(ReadOnlySpan`1 utf8Json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](ReadOnlySpan`1 utf8Json, JsonSerializerOptions options)
   at Amazon.Lambda.Serialization.SystemTextJson.DefaultLambdaJsonSerializer.Deserialize[T](Stream requestStream)
```
### Environment

```xml
    <PackageReference Include="Amazon.Lambda.Core" Version="1.1.0" />
    <PackageReference Include="Amazon.Lambda.Serialization.SystemTextJson" Version="2.0.1" />
    <PackageReference Include="AWSSDK.CodePipeline" Version="3.5.1.5" />
    <PackageReference Include="AWSSDK.S3" Version="3.5.5.2" />
```
Lambda

## Resolution

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment] 2020-12-01 20:44
Hi @ingun37,

 Good afternoon.

In order to troubleshoot the issue, please let me know the reference/guide from where `CodePipelineEvent` definition as determined. There appears to be some mismatched mapping that resulted in above exception.

Thanks,
Ashish

**Comment by ashishdhingra** [comment] 2020-12-01 22:40
Hi @ingun37,

Upon examining it further, the cause of the error is that [Amazon.CodePipeline.Model.ArtifactLocation.Type](https://github.com/aws/aws-sdk-net/blob/de5387dc746d303f0f62db0fc541ce599f9e7ed5/sdk/src/Services/CodePipeline/Generated/Model/ArtifactLocation.cs#L63) is of  type `ArtifactLocationType`, whereas the `type` JSON property in the below example CodePipeline event input JSON is of type `string`:
```JSON
{
  "CodePipeline.job": {
    "id": "c968ef10-6415-4127-80b1-42502218a8c7",
    "accountId": "123456789012",
    "data": {
      "actionConfiguration": {
        "configuration": {
          "FunctionName": "my-function",
          "UserParameters": "user-parameter-string"
        }
      },
      "inputArtifacts": [
        {
          "name": "input-artifact",
          "location": {
            "type": "S3",
            "s3Location": {
              "objectKey": "my-pipeline/input-artifact/jjmtQ59",
              "bucketName": "codepipeline-{region}-12345678901"
            }
          },
          "revision": "ca2bdeadbeef7d1932acb4977e08c803295d9896"
        }
      ],
      "outputArtifacts": [
        {
          "name": "output-artifact",
          "location": {
            "type": "S3",
            "s3Location": {
              "objectKey": "test-lambda/output-artifact/ggjsOC9",
              "bucketName": "codepipeline-{region}-12345678901"
            }
          },
          "revision": null
        }
      ],
      "artifactCredentials": {
        "accessKeyId": "AKIAIOSFODNN7EXAMPLE",
        "secretAccessKey": "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY",
        "sessionToken": "token"
      }
    }
  }
}
```

You might have to write full-fledged custom class for CodePipelineEvent (refer [SQSEvent](https://github.com/aws/aws-lambda-dotnet/blob/master/Libraries/src/Amazon.Lambda.SQSEvents/SQSEvent.cs) as an example) **and/or** custom `JsonConverter` which converts `string` to `ArtifactLocationType` type.

Please let me know if this works.

Thanks,
Ashish

**Comment by ingun37** [comment] 2020-12-02 13:12
I ended up writing full-fledged class like you said although it would have been nicer if I hadn’t had to but I’m happy overall with the resolution.

Is it going to be fixed in the future?

**Comment by ashishdhingra** [comment] 2020-12-02 16:15
Hi @ingun37,

The SDK Model class `ArtifactLocationType` is auto-generated. Hence, I do not see it to be fixed in near future. Basically its the problem with the CodePipeline returning string but model class expecting it of a certain type. Hence the problem with the serialization process from JSON. Unfortunately, these types of constant classes cannot be represented in JSON. The workaround as mentioned earlier, is to write custom class (which you implemented) and/or write custom `JsonConverter`.

Thanks,
Ashish

**Closed by ashishdhingra** 2020-12-02 16:15 UTC
Labels: bug, module/lambda-client-lib, response-requested
