### ISSUE TITLE
RabbitMQEvent Serialization error

### ISSUE THREAD

**Issue by milkfrog** [aws/aws-lambda-dotnet#1562] opened 2023-08-09 13:47 UTC
### Describe the bug

Hello!
I'm trying to use the `RabbitMQEvent` input type in my Lambda Function to consume from an AmazonMQ (RabbitMQ) instance, but there's a bug in the serialization process.

### Expected Behavior

I expect to be able to serialize the input correctly using RabbitMQEvent as my input type.

### Current Behavior

Following is the error log that I got from CloudWatch:

> 2023-08-09T13:37:24.840Z	f72c9cf5-4d2a-47fc-9dd3-82a787cd29ab	fail	Amazon.Lambda.Serialization.SystemTextJson.JsonSerializerException: Error converting the Lambda event JSON payload to type Amazon.Lambda.MQEvents.RabbitMQEvent: The JSON value could not be converted to System.Int32. Path: $.rmqMessagesByQueue['app1-to-lambda::/'][0].basicProperties.priority | LineNumber: 0 | BytePositionInLine: 325.
 ---> System.Text.Json.JsonException: The JSON value could not be converted to System.Int32. Path: $.rmqMessagesByQueue['app1-to-lambda::/'][0].basicProperties.priority | LineNumber: 0 | BytePositionInLine: 325.
 ---> System.InvalidOperationException: Cannot get the value of a token type 'Null' as a number.
   at System.Text.Json.Utf8JsonReader.TryGetInt32(Int32& value)
   at System.Text.Json.Utf8JsonReader.GetInt32()
   at System.Text.Json.Serialization.Converters.Int32Converter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonDictionaryConverter`3.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TDictionary& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](ReadOnlySpan`1 utf8Json, JsonSerializerOptions options)
   at Amazon.Lambda.Serialization.SystemTextJson.DefaultLambdaJsonSerializer.InternalDeserialize[T](Byte[] utf8Json)
   at Amazon.Lambda.Serialization.SystemTextJson.AbstractLambdaJsonSerializer.Deserialize[T](Stream requestStream)
   --- End of inner exception stack trace ---
   at Amazon.Lambda.Serialization.SystemTextJson.AbstractLambdaJsonSerializer.Deserialize[T](Stream requestStream)
   at lambda_method1(Closure , Stream , ILambdaContext , Stream )
   at Amazon.Lambda.RuntimeSupport.Bootstrap.UserCodeLoader.Invoke(Stream lambdaData, ILambdaContext lambdaContext, Stream outStream) in /src/Repo/Libraries/src/Amazon.Lambda.RuntimeSupport/Bootstrap/UserCodeLoader.cs:line 145
   at Amazon.Lambda.RuntimeSupport.HandlerWrapper.<>c__DisplayClass8_0.<GetHandlerWrapper>b__0(InvocationRequest invocation) in /src/Repo/Libraries/src/Amazon.Lambda.RuntimeSupport/Bootstrap/HandlerWrapper.cs:line 55
   at Amazon.Lambda.RuntimeSupport.LambdaBootstrap.InvokeOnceAsync(CancellationToken cancellationToken) in /src/Repo/Libraries/src/Amazon.Lambda.RuntimeSupport/Bootstrap/LambdaBootstrap.cs:line 176

### Reproduction Steps

1) Create an AmazonMQ instance using RabbitMQ (version 3.11.16);
2) Create and deploy a Lambda Function using C# and the RabbitMQEvent type as input;
3) Add the MQ trigger and publish some message;

### AWS .NET SDK and/or Package version used

Amazon.Lambda.Core 2.1.0
Amazon.Lambda.MQEvents 1.1.0

### Targeted .NET Platform

.NET 6

### Operating System and version

Windows 11

**Comment by ashishdhingra** [comment] 2023-08-09 17:25
@milkfrog Could you please add environment variable `LAMBDA_NET_SERIALIZER_DEBUG` and set it's value to `true` in your Lambda execution environment, so that input and output JSON is logged (refer [Updates for .NET Core Lambda Libraries](https://aws.amazon.com/blogs/developer/updates-for-net-core-lambda-libraries/))? Thereafter, please share the input event JSON for RabbitMQ for further inspection.

Thanks,
Ashish

**Comment by ashishdhingra** [comment] 2023-08-10 21:21
@milkfrog Good afternoon. I was able to reproduce the issue using the below steps:
- Followed steps mentioned in https://aws.amazon.com/blogs/compute/using-amazon-mq-for-rabbitmq-as-an-event-source-for-lambda/ to create broker, create queue, IAM role for Lambda and secret (containing `username` and `password` configured while creating broker). IAM role has at least below permissions (in addition to `AWSLambdaBasicExecutionRole` which grants access to write to CloudWatch logs):
```
mq:DescribeBroker
secretsmanager:GetSecretValue
ec2:CreateNetworkInterface
ec2:DescribeNetworkInterfaces
ec2:DescribeVpcs
ec2:DeleteNetworkInterface
ec2:DescribeSubnets
ec2:DescribeSecurityGroups
```
- Created new Lambda function (.NET 6) with the code mentioned in `Amazon.Lambda.MQEvents` [Readme](https://github.com/aws/aws-lambda-dotnet/tree/master/Libraries/src/Amazon.Lambda.MQEvents).
- During deployment of Lambda function,
  - Selected the newly created IAM role.
  - Defined environment variable `LAMBDA_NET_SERIALIZER_DEBUG` with value `true`.
- After the function was deployed, in function configuration, added a new `MQ` trigger with batch size `1`.

First published new message without setting `priority` property value. The CloudWatch logs reported the same error:
```
Amazon.Lambda.Serialization.SystemTextJson.JsonSerializerException: Error converting the Lambda event JSON payload to type Amazon.Lambda.MQEvents.RabbitMQEvent: The JSON value could not be converted to System.Int32. Path: $.rmqMessagesByQueue['TestQueue::/'][0].basicProperties.priority | LineNumber: 0 | BytePositionInLine: 264.
 ---> System.Text.Json.JsonException: The JSON value could not be converted to System.Int32. Path: $.rmqMessagesByQueue['TestQueue::/'][0].basicProperties.priority | LineNumber: 0 | BytePositionInLine: 264.
 ---> System.InvalidOperationException: Cannot get the value of a token type 'Null' as a number.
   at System.Text.Json.Utf8JsonReader.TryGetInt32(Int32& value)
   at System.Text.Json.Utf8JsonReader.GetInt32()
   at System.Text.Json.Serialization.Converters.Int32Converter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonDictionaryConverter`3.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TDictionary& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](ReadOnlySpan`1 utf8Json, JsonSerializerOptions options)
   at Amazon.Lambda.Serialization.SystemTextJson.DefaultLambdaJsonSerializer.InternalDeserialize[T](Byte[] utf8Json)
   at Amazon.Lambda.Serialization.SystemTextJson.AbstractLambdaJsonSerializer.Deserialize[T](Stream requestStream)
   --- End of inner exception stack trace ---
   at Amazon.Lambda.Serialization.SystemTextJson.AbstractLambdaJsonSerializer.Deserialize[T](Stream requestStream)
   at lambda_method1(Closure , Stream , ILambdaContext , Stream )
   at Amazon.Lambda.RuntimeSupport.Bootstrap.UserCodeLoader.Invoke(Stream lambdaData, ILambdaContext lambdaContext, Stream outStream) in /src/Repo/Libraries/src/Amazon.Lambda.RuntimeSupport/Bootstrap/UserCodeLoader.cs:line 145
   at Amazon.Lambda.RuntimeSupport.HandlerWrapper.<>c__DisplayClass8_0.<GetHandlerWrapper>b__0(InvocationRequest invocation) in /src/Repo/Libraries/src/Amazon.Lambda.RuntimeSupport/Bootstrap/HandlerWrapper.cs:line 55
   at Amazon.Lambda.RuntimeSupport.LambdaBootstrap.InvokeOnceAsync(CancellationToken cancellationToken) in /src/Repo/Libraries/src/Amazon.Lambda.RuntimeSupport/Bootstrap/LambdaBootstrap.cs:line 208
```
It also logged the below input event JSON:
```JSON
{
    "eventSourceArn": "arn:aws:mq:us-east-2:139480602983:broker:testrabbitmqbroker:b-c82a48a0-a342-492c-acc2-18f3d6538810",
    "rmqMessagesByQueue": {
        "TestQueue::/": [
            {
                "basicProperties": {
                    "contentType": null,
                    "contentEncoding": null,
                    "headers": {},
                    "deliveryMode": 1,
                    "priority": null,
                    "correlationId": null,
                    "replyTo": null,
                    "expiration": null,
                    "messageId": null,
                    "timestamp": null,
                    "type": null,
                    "userId": null,
                    "appId": null,
                    "clusterId": null,
                    "bodySize": 11
                },
                "redelivered": true,
                "data": "SGVsbG8gV29ybGQ="
            }
        ]
    },
    "eventSource": "aws:rmq"
}
```

Notice that the value of `priority` is `null`. Since the [RabbitMQMessage.BasicProperties.Priority](https://github.com/aws/aws-lambda-dotnet/blob/0b3e1bf54e20ed0cc9a45ce2510fb37b4893abab/Libraries/src/Amazon.Lambda.MQEvents/RabbitMQEvent.cs#L77C24-L77C32) is not nullable, the serialization fails.

Then a new message was sent with `priority` value set to `40` (for example). The function execution succeeded. Following input event JSON was logged:
```JSON
{
    "eventSourceArn": "arn:aws:mq:us-east-2:139480602983:broker:testrabbitmqbroker:b-c82a48a0-a342-492c-acc2-18f3d6538810",
    "rmqMessagesByQueue": {
        "TestQueue::/": [
            {
                "basicProperties": {
                    "contentType": null,
                    "contentEncoding": null,
                    "headers": {},
                    "deliveryMode": 1,
                    "priority": 40,
                    "correlationId": null,
                    "replyTo": null,
                    "expiration": null,
                    "messageId": null,
                    "timestamp": null,
                    "type": null,
                    "userId": null,
                    "appId": null,
                    "clusterId": null,
                    "bodySize": 11
                },
                "redelivered": false,
                "data": "SGVsbG8gV29ybGQ="
            }
        ]
    },
    "eventSource": "aws:rmq"
}
```

So the fix would be change underlying type for [RabbitMQMessage.BasicProperties.Priority](https://github.com/aws/aws-lambda-dotnet/blob/0b3e1bf54e20ed0cc9a45ce2510fb37b4893abab/Libraries/src/Amazon.Lambda.MQEvents/RabbitMQEvent.cs#L77C24-L77C32) to nullable `int?`.

Kindly note that this could be a breaking change, which would be mentioned in the changelog once the fix is pushed.

Thanks,
Ashish

**Comment by ashishdhingra** [comment] 2023-08-24 16:26
> May I inquire about the estimated release date for the update that addresses this particular bug?

@YonathanRodriguez I would discuss with the team today and hopefully we could release the changes this week.

**Comment by ashishdhingra** [comment] 2023-08-25 15:52
Fixed in [Amazon.Lambda.MQEvents version 2.0.0](https://www.nuget.org/packages/Amazon.Lambda.MQEvents/2.0.0).

**Closed by ashishdhingra** 2023-08-25 15:52 UTC
Labels: bug, module/lambda-client-lib, queued, p2

**Comment by d-vs** [comment] 2023-08-28 08:10
@ashishdhingra This is marked as fixed, but there is an identical problem with the delivery-mode property.

**Comment by ashishdhingra** [comment] 2023-08-28 08:22
> @ashishdhingra This is marked as fixed, but there is an identical problem with the delivery-mode property.

@d-vs Based on end-to-end testing from RabbitMQ web UI, delivery mode is a drop-down and hence cannot be omitted. So it’s value should always be present. Kindly advise on how you are testing end-to-end.

**Comment by d-vs** [comment] 2023-08-28 08:29
@ashishdhingra thanks for the quick reply. I'm unsure which UI you refer to, but in real world scenarios nobody uses the UI to publish messages, but rather the RabbitMQ.Client NuGet package, or some derivative of this (MassTransit for example). 

That library treats default type values, 0 for int for example, as not having been set, and simply omits to publish the property if so. I regard that as a bug in that library, but AWS lambda events could be more robust in handling such things.

**Comment by ashishdhingra** [comment] 2023-08-28 08:53
> @ashishdhingra thanks for the quick reply. I'm unsure which UI you refer to, but in real world scenarios nobody uses the UI to publish messages, but rather the RabbitMQ.Client NuGet package, or some derivative of this (MassTransit for example).
> 
> That library treats default type values, 0 for int for example, as not having been set, and simply omits to publish the property if so. I regard that as a bug in that library, but AWS lambda events could be more robust in handling such things.

@d-vs Please refer https://www.rabbitmq.com/consumers.html. 



Property | Type | Description | Required?
-- | -- | -- | --
Delivery mode | Enum (1 or 2) | 2 for "persistent", 1 for "transient". Some client libraries expose this property as a boolean or enum. | Yes

Delivery mode is an Enumeration which could have value `1` or `2`. It cannot have value `0` or `null`.

**Comment by d-vs** [comment] 2023-08-28 08:56
@ashishdhingra Hmm, this is interesting, because their own client library does not enforce this. But I suppose this doc means AWS is free of having to cater for 0/null. Thanks
