### ISSUE TITLE
Unable to run ASP.NET Core Web API serverless app blueprint in Visual Studio 2017

### ISSUE THREAD

**Issue by atroder** [aws/aws-lambda-dotnet#125] opened 2017-05-29 06:44 UTC
I can successfully run the ASP.NET Core Web API blueprint in the Visual Studio 2015 AWS Serverless Application template. However, when I try this from Visual Studio 2017 Enterprise, I get an unhandled exception reported in the application console when issuing a simple GET against the s3proxy controller. If I remove the IAmazonS3 argument from the S3ProxyController constructor, the problem goes away.

I have installed the latest preview of the AWS Toolkit for Visual Studio 2017.

Please advise.

**Comment by normj** [comment] 2017-06-02 05:44
Is there any information like a stack trace in the CloudWatch logs associated with the Lambda function?

**Comment by atroder** [comment] 2017-06-02 07:08
Thank you for the response. I'm actually running the project locally to test it out before I deploy it to cloud. Just wondering if there is any recent incompatibility between VS 2017 and AWS Toolkit Preview. The problem really seems to be centered around trying to inject the IAmazonS3 binding into the S3ProxyController constructor. I also tried to inject an IAmazonDynamoDB binding with the same result. I verified that I have the correct AWS nuget packages installed as well. Again, no problems doing this in VS 2015 which is what I am using with success.

**Comment by ChristianAvila** [comment] 2017-08-08 22:13
I have the same issue, this is the stack trace 

Error: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Amazon.Extensions.NETCore.Setup.ClientFactory.CreateClient(Type serviceInterfaceType, AWSCredentials credentials, ClientConfig config)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.Internal.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.TypeActivatorCache.CreateInstance[TInstance](IServiceProvider serviceProvider, Type implementationType)
   at Microsoft.AspNetCore.Mvc.Controllers.DefaultControllerFactory.CreateController(ControllerContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.
<InvokeAllActionFiltersAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.
    <InvokeExceptionFilterAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.
        <InvokeAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.
            <Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.
                <Invoke>d__6.MoveNext()

**Comment by normj** [comment] 2017-08-24 07:03
@ChristianAvila Was there an inner exception? I'm wondering if we can figure out what the error was with the reflection InvokeMethod.

**Comment by normj** [comment] 2017-12-22 01:19
Closing for lack activity and unable to reproduce the issue

**Closed by normj** 2017-12-22 01:19 UTC
Labels: Question
