### ISSUE TITLE
The last few log lines are missing rarely in 3.1

### ISSUE THREAD

**Issue by mhelbig-oz** [aws/aws-lambda-dotnet#753] opened 2020-10-22 17:27 UTC
## Description
When running a lambda, rarely some ending log lines are missing from the CloudWatch output. I did not see this behavior in 2.1, and I am seeing this behavior in 3.1.

## Reproduction Steps
Create a lambda with the attached code. Assign it a role that allows writing to CloudWatch and launching lambdas. Set up a CloudWatch event to invoke the lambda every 20 minutes with an empty input. Give it a 900 second timeout. Export the logs from CloudWatch and notice rarely the line 'Finished 'ReproMissingLogs' with RequestId' will be missing from the output.

To build the lambda you need to add Newtonsoft and AWSSDK.Lambda via nuget.

[Function.zip](https://github.com/aws/aws-lambda-dotnet/files/5424536/Function.zip)

### Logs
Here is an example of a failure case:
```
2020-10-21T21:57:08.463Z START RequestId: d9512f18-cdb5-479d-ab43-e8addfd2f272 Version: $LATEST

2020-10-21T21:57:08.468Z Starting 'ReproMissingLogs' with RequestId 'd9512f18-cdb5-479d-ab43-e8addfd2f272'. Input: {"BuildStep":1,"WorkIndex":2}.
2020-10-21T21:57:09.531Z Starting work 2...
2020-10-21T21:57:09.531Z Work will take 39699 milliseconds
2020-10-21T21:57:49.246Z END RequestId: d9512f18-cdb5-479d-ab43-e8addfd2f272

2020-10-21T21:57:49.246Z REPORT RequestId: d9512f18-cdb5-479d-ab43-e8addfd2f272	Duration: 40786.58 ms	Billed Duration: 40800 ms	Memory Size: 256 MB	Max Memory Used: 70 MB	Init Duration: 261.47 ms	

```

Here is an example of a success case:
```
2020-10-21T21:37:09.886Z START RequestId: 64963e8f-1cc0-4458-aaa9-36569dfb5031 Version: $LATEST

2020-10-21T21:37:09.894Z Starting 'ReproMissingLogs' with RequestId '64963e8f-1cc0-4458-aaa9-36569dfb5031'. Input: {"BuildStep":1,"WorkIndex":16}.
2020-10-21T21:37:10.919Z Starting work 16...
2020-10-21T21:37:10.919Z Work will take 8827 milliseconds
2020-10-21T21:37:19.748Z Finished work
2020-10-21T21:37:19.750Z Finished 'ReproMissingLogs' with RequestId '64963e8f-1cc0-4458-aaa9-36569dfb5031' with '890.136' seconds left.
2020-10-21T21:37:19.750Z END RequestId: 64963e8f-1cc0-4458-aaa9-36569dfb5031

2020-10-21T21:37:19.750Z REPORT RequestId: 64963e8f-1cc0-4458-aaa9-36569dfb5031	Duration: 9864.03 ms	Billed Duration: 9900 ms	Memory Size: 256 MB	Max Memory Used: 69 MB	Init Duration: 161.26 ms
```

### Environment

* Build Version: Amazon.Lambda.Core 1.1.0, Amazon.Lambda.Serialization.SystemTextJson 2.0.0, AWSSDK.Lambda 3.3.110.18
* OS Info: Built and Deployed on Windows 10
* Build Environment: Visual Studio
* Targeted .NET Platform:  .NET Core 3.1

## Resolution
- [ ] :wave: I can/would-like-to implement a fix for this problem myself

Find and fix what is causing these missing logs.

I reported this as [issue 717](https://github.com/aws/aws-lambda-dotnet/issues/717) but haven't had a chance to write a reproduction until now.

I did notice I'm a bit behind on Nuget packages. I will update and see if it is still reproducing, but unless something has been fixed I suspect this is still a problem.

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment] 2020-10-22 19:54
Hi @mhelbig-oz,

Thanks for posting the issue. From high level, it appears that you are invoking a Lambda where input stream has initial flag of `DistributeWork` and then executing number of requests to invoke the same Lambda with flag `DoWork`. As you mentioned, the issue happens rarely, hence, could you try to add some basic exception handling in this example to see if some invocation errors or runtime error might be causing issue for missing log lines in the CloudWatch log stream? This doesn't appear to be a bug in AWS Lambda but merely a runtime error condition or thread race condition, which might not be captured in the log.

Without concrete reproduction, it might not be possible to identify the root cause. Kindly note that Lambda invocation errors happen outside the SDK, hence, you might want to check the CloudTrail logs.

Thanks,
Ashish

**Comment by mhelbig-oz** [comment] 2020-10-22 20:33
Hey @ashishdhingra 

This is an incredibly frustrating response. Our company has already spent considerable time writing up a repro case for you. If you look at the file, it doesn't do anything that could possibly cause an exception to be thrown. DoWork is simply doing a Sleep and then logging. If an exception is being thrown, it's being thrown by something AWS is responsible for (the code that does the logging, the code responsible for hosting the lambda itself). CloudWatch metrics shows a success rate of 100% since this lambda started being run. In every time I've seen this in the wild I've looked at the results of the lambda and it appears to have completed its work successfully. 

This is a concrete reproduction. I wrote this up and it reproduced in 40 minutes with my steps. I provided a log example of it reproducing. I provided the setup examples. My company is literally paying you money right now to continue to reproduce this. I could update this bug with examples of this failing every day.

**Comment by ashishdhingra** [comment] 2020-10-22 20:43
@mhelbig-oz I do see that the code shared by you doesn't do anything special that would cause any kind of exception. However, the Lambda invocation errors occur outside of the SDK; refer the article [How do I troubleshoot Lambda function failures?](https://aws.amazon.com/premiumsupport/knowledge-center/lambda-troubleshoot-function-failures/) for detailed information.

I will try to reproduce the issue at my end. It would be helpful if you could share the following:
- Sample initial JSON
- How is Lambda (initially and subsequently) triggered? If there any automation script?
- Are there any errors logged in CloudWatch (for code related errors)? (I'm assuming there are none)

Thanks,
Ashish

**Comment by mhelbig-oz** [comment] 2020-10-22 20:44
- In the initial post
- In the initial post
- No

**Comment by mhelbig-oz** [comment] 2020-10-23 15:55
Here are a couple more repros from yesterday. It reproed 2 out of 1510 times to give a number associated with rare:
```
2020-10-22T19:17:10.088Z START RequestId: 40c58d15-00be-4897-ba4d-e64dd3e48a6e Version: $LATEST

2020-10-22T19:17:10.122Z Starting 'ReproMissingLogs' with RequestId '40c58d15-00be-4897-ba4d-e64dd3e48a6e'. Input: {"BuildStep":1,"WorkIndex":15}.
2020-10-22T19:17:11.145Z Starting work 15...
2020-10-22T19:17:11.145Z Work will take 30318 milliseconds
2020-10-22T19:17:41.507Z END RequestId: 40c58d15-00be-4897-ba4d-e64dd3e48a6e

2020-10-22T19:17:41.507Z REPORT RequestId: 40c58d15-00be-4897-ba4d-e64dd3e48a6e	Duration: 31418.47 ms	Billed Duration: 31500 ms	Memory Size: 256 MB	Max Memory Used: 69 MB	Init Duration: 157.72 ms	
```

```
2020-10-22T09:17:08.255Z START RequestId: f63d8e91-2af0-4942-904b-bd18a695fb99 Version: $LATEST

2020-10-22T09:17:08.274Z Starting 'ReproMissingLogs' with RequestId 'f63d8e91-2af0-4942-904b-bd18a695fb99'. Input: {"BuildStep":1,"WorkIndex":5}.
2020-10-22T09:17:09.274Z Starting work 5...
2020-10-22T09:17:09.293Z Work will take 20226 milliseconds
2020-10-22T09:17:29.521Z Finished work
2020-10-22T09:17:29.524Z END RequestId: f63d8e91-2af0-4942-904b-bd18a695fb99

2020-10-22T09:17:29.524Z REPORT RequestId: f63d8e91-2af0-4942-904b-bd18a695fb99	Duration: 21267.80 ms	Billed Duration: 21300 ms	Memory Size: 256 MB	Max Memory Used: 69 MB	Init Duration: 161.80 ms
```

More evidence about this not actually being an error, and instead being missing logs. The lambda retry mechanism never kicks in for these cases either.

**Comment by hunanniu** [comment] 2020-12-14 03:22
We believe the issue is on Lambda service side rather than in SDK. So we will close this one. If Lambda thinks otherwise after they investigate, you can reopen.

**Closed by hunanniu** 2020-12-14 03:22 UTC
Labels: A, bug, module/lambda-client-lib, queued

**Comment by mhelbig-oz** [comment] 2020-12-14 17:45
@hunanniu Can you please link the new issue instead of just closing an issue with no way for the client to follow up?

**Comment by dan-glenn-ivendi** [comment] 2021-07-16 09:21
@hunanniu Could you link to the new issue (Lambda) please?
