### ISSUE TITLE
Deserialization error in Cognito triggered lambda for CUSTOM_AUTH flow

### ISSUE THREAD

**Issue by ankushjain358** [aws/aws-lambda-dotnet#1644] opened 2023-12-19 13:06 UTC
### Describe the bug

To enable CUSTOM_AUTH flow, I created below 3 Lambda functions in .NET, and used `Amazon.Lambda.CognitoEvents` NuGet package v2.2.0 for input events.
- DefineAuthChallenge
- CreateAuthChallenge
- VerifyAuthChallenge

Out of above 3, two Lambda functions are failing while deserializing incoming event JSON to .NET type. It seems that Cognito is sending boolean values as null, while respective .NET properties are not nullable.

Here are the .NET Types which are creating issue:
- CognitoDefineAuthChallengeEvent
  -  `response.issueTokens` should be nullable
  - `response.failAuthentication` should be nullable
- CognitoVerifyAuthChallengeEvent
  - `response.answerCorrect`  should be nullable
  

### Expected Behavior

The .NET Lambda function should be triggered with the incoming event JSON without any error.

### Current Behavior

The .NET Lambda function fails for the following triggers when using types defined in `Amazon.Lambda.CognitoEvents` library.
- Cognito > Custom authentication> Define auth challenge
- Cognito > Custom authentication > Verify auth challenge response

### Reproduction Steps

Create lambda function as per below syntax for Cognito triggers.

1. DefineAuthChallenge
    ```cs
    public CognitoDefineAuthChallengeEventCustom DefineAuthChallenge(CognitoDefineAuthChallengeEvent challengeEvent)
    {
       ...
    }
    ```

2. VerifyAuthChallenge
    ```cs
    public CognitoVerifyAuthChallengeEventCustom VerifyAuthChallenge(CognitoVerifyAuthChallengeEventCustom challengeEvent)
    {
      ...
    }
    ```

Use the following JSON as input event, just make the boolean fields `null`.

- [cognito-defineauthchallenge-event.json](https://github.com/aws/aws-lambda-dotnet/blob/9a0d0b4e4da636cdf3453f17464fd3dc4b1a8bd3/Libraries/test/EventsTests.Shared/cognito-defineauthchallenge-event.json)
- [cognito-verifyauthchallenge-event.json](https://github.com/aws/aws-lambda-dotnet/blob/9a0d0b4e4da636cdf3453f17464fd3dc4b1a8bd3/Libraries/test/EventsTests.Shared/cognito-verifyauthchallenge-event.json)

### Possible Solution
Update boolean properties to nullable boolean.

- CognitoDefineAuthChallengeEvent
  -  `response.issueTokens` should be nullable
  - `response.failAuthentication` should be nullable
- CognitoVerifyAuthChallengeEvent
  - `response.answerCorrect`  should be nullable

### Additional Information/Context
![1  DefineAuthChallengeEvent](https://github.com/aws/aws-lambda-dotnet/assets/13661966/990ce185-c5fd-4984-acab-d7128857338f)
![2  VerifyAuthChallege Event](https://github.com/aws/aws-lambda-dotnet/assets/13661966/3e9cfc9b-0fec-4997-95b5-7dc53e372886)
![3  Local error](https://github.com/aws/aws-lambda-dotnet/assets/13661966/328ecc88-f161-4e5f-abaa-f7bac1bb79bf)
![4  Error in CloudWatch](https://github.com/aws/aws-lambda-dotnet/assets/13661966/937c0a15-16e5-4fca-bc30-c1ad046a2174)

### AWS .NET SDK and/or Package version used

```xml
<ItemGroup>
	<PackageReference Include="Amazon.Lambda.CognitoEvents" Version="2.2.0" />
	<PackageReference Include="Amazon.Lambda.Core" Version="2.2.0" />
	<PackageReference Include="Amazon.Lambda.Serialization.SystemTextJson" Version="2.4.0" />
	<PackageReference Include="Amazon.Lambda.Annotations" Version="1.0.0" />
	<PackageReference Include="AWS.Lambda.Powertools.Logging" Version="1.4.4" />
</ItemGroup>
```

### Targeted .NET Platform

.NET 6

### Operating System and version

Windows 10, Amazon Linux 2

**Comment by ashishdhingra** [comment] 2023-12-19 17:50
Most likely the model from Cognito events changed and the corresponding POCO class needs an update.

**Comment by ashishdhingra** [comment] 2023-12-19 22:45
@ankushjain358 Good afternoon. Here are my observations:
- If you refer page [Verify Auth challenge response Lambda trigger](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-verify-auth-challenge-response.html), for `answerCorrect`, If the user successfully completes the challenge, Amazon Cognito sets the attribute value to `true`. If the user doesn't successfully complete the challenge, Amazon Cognito sets the value to `false`. There is also an [example](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-define-auth-challenge.html#aws-lambda-triggers-define-auth-challenge-example) which demonstrates how to set the value for `answerCorrect` parameter.
  It doesn't specify under which conditions, the value of `answerCorrect` would be `null`.
- If you refer [Define Auth challenge Lambda trigger](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-define-auth-challenge.html), 
  - For `issueTokens`, If you determine that the user has completed the authentication challenges sufficiently, set to `true`. If the user has not met the challenges sufficiently, set to `false`.
  - For `failAuthentication`, If you want to end the current authentication process, set to `true`. To continue the current authentication process, set to `false`.
  It doesn't specify guidance setting null to these values. The page also has an [example](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-define-auth-challenge.html#aws-lambda-triggers-define-auth-challenge-example), which demonstrates how to set the values. 

Please confirm the following:
- Is your use case is that the default event object set by Cognito has `null` for these values having issue and that the Lambda Cognito Event POCO classes should allow `null` values for these fields?
- Is it possible to share end-to-end setup (without manually using customized response JSON) with steps, so that we could reproduce the issue at our end?
- Is it possible to contribute a PR for the fix (the fix appears to be pretty trivial) along with unit test cases?

Thanks,
Ashish

**Comment by ankushjain358** [comment] 2023-12-20 09:55
**Is your use case is that the default event object set by Cognito has null for these values having issue and that the Lambda Cognito Event POCO classes should allow null values for these fields?**
Yes

**Is it possible to share end-to-end setup (without manually using customized response JSON) with steps, so that we could reproduce the issue at our end?**
Steps to reproduce this issue.
- Unzip attached [cognito-lambda-triggers-demo.zip](https://github.com/aws/aws-lambda-dotnet/files/13725692/cognito-lambda-triggers-demo.zip)
- Run the following commands to deploy the stack,
  ```
  sam build
  sam deploy
  ```
- Run the following commands to perform CUSTOM_AUTH flow, and generate event logs in CloudWatch.
  ```
  aws cognito-idp initiate-auth --client-id YOUR_CLIENT_ID --auth-flow CUSTOM_AUTH --auth-parameters USERNAME=admin@example.com
  
  aws cognito-idp respond-to-auth-challenge --client-id YOUR_CLIENT_ID --challenge-name CUSTOM_CHALLENGE --challenge-responses USERNAME=admin@example.com,ANSWER="Cricket" --session "SESSION_TOKEN"
  ```
- After running above commands, go to CloudWatch Log Groups, and see the logged event JSON.

**Is it possible to contribute a PR for the fix (the fix appears to be pretty trivial) along with unit test cases?**
Yes, I will raise it soon.

**Comment by ankushjain358** [comment] 2024-01-02 12:47
@ashishdhingra - Any update here?

**Comment by ashishdhingra** [comment] 2024-01-05 17:52
@ankushjain358 Could you please share sample JSON for testing in text format (not the image)?

**Comment by ankushjain358** [comment] 2024-01-05 18:11
@ashishdhingra I have provided entire sample in zip file with the steps to reproduce in one of above comments. Can you please just deploy the zipped solution using SAM and reproduce the issue. That way you will also get the event JSON from CloudWatch.

**Comment by ashishdhingra** [comment] 2024-01-05 19:11
> @ashishdhingra I have provided entire sample in zip file with the steps to reproduce in one of above comments. Can you please just deploy the zipped solution using SAM and reproduce the issue. That way you will also get the event JSON from CloudWatch.

@ankushjain358 I reviewed this with the team. Since you have reproduced it end-to-end, we would instead write the unit test case against the JSON you share and make changes to POCO classes. Feel free to contribute PR so that this could be merged to library soon. This would be a breaking change since we are changing data types and would require major version bump, including call out in changelog.

**Comment by ankushjain358** [comment] 2024-01-08 08:02
@ashishdhingra - I've created a pull request to address the issue.

Also, I don't believe this would require changes to test cases because I've seen a few other events with nullable bool properties, such as `KinesisTimeWindowEvent`, `ActiveMQMessage`, and others, that do not maintain separate event JSON files to test against null values.

PR Link - https://github.com/aws/aws-lambda-dotnet/pull/1646

**Comment by ashovlin** [comment] 2024-01-23 15:15
Thanks again for the PR! This has been released in Amazon.Lambda.CognitoEvents v3.0.0.

**Closed by ashovlin** 2024-01-23 15:15 UTC
Labels: bug, module/lambda-client-lib, queued, p2, s
