### ISSUE TITLE
.Net Core 2.1 Resx - File Resources

### ISSUE THREAD

**Issue by CodeRevver** [aws/aws-lambda-dotnet#445] opened 2019-04-16 17:07 UTC
I use resx files in my application to easily extract Sql as strings.  When my code runs on Lambda, the Resource I pull back with my code returns me an incorrect value.

Here's an example,

**IdeaQueries.resx contains:**
After adding a reference to a file to my resx I get the following in my xml.
```
<data name="VoteIdea" type="System.Resources.ResXFileRef, System.Windows.Forms">
  <value>VoteIdea.sql;System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089;utf-8</value>
</data>
```

IdeaQueries.resx file is just a resx that references the VoteIdea.sql file.  It's access modifier is Public.

**Code contains:**
`var test = IdeaQueries.VoteIdea;` 

**When I run this Locally**, my code returns the sql contained in file - which is expected.  

**On Lambda it incorrectly returns:** 
`VoteIdea.sql;System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089;utf-8`

I'm going to try and work round this issue by embedding the sql and accessing it that way, but it really sucks to have to work around this issue - referencing the Sql from the ResX is by far the most optimal solution to my mind.

**Comment by pclancysc** [comment] 2019-07-25 09:08
Same issue, any update on this?

**Comment by ashishdhingra** [comment] 2020-10-07 18:50
Hi @CodeRevver,

Good morning.

I was going through the issue backlog and came across this one. Unfortunately, I'm unable to reproduce the issue. I used the following code example:
```C#
using System.Reflection;

using Amazon.Lambda.Core;
using AWS.Logger.Log4net;
using log4net;
using log4net.Config;
using log4net.Core;
using log4net.Layout;
using log4net.Repository.Hierarchy;

// Assembly attribute to enable the Lambda function's JSON input to be converted into a .NET class.
[assembly: LambdaSerializer(typeof(Amazon.Lambda.Serialization.Json.JsonSerializer))]

namespace MyFunction
{
    public class Function
    {
        public Function()
        {
            XmlConfigurator.Configure(LogManager.GetRepository(Assembly.GetEntryAssembly()), new System.IO.FileInfo("log4net.config"));

            ILog log = LogManager.GetLogger(typeof(Function));
            log.Info("Check the AWS Console CloudWatch Logs console in us-east-2");
            log.Info("to see messages in the log streams for the");
            log.Info("log group /aws/lambda/MyFunction");
        }
        
        /// <summary>
        /// A simple function that takes a string and does a ToUpper
        /// </summary>
        /// <param name="input"></param>
        /// <param name="context"></param>
        /// <returns></returns>
        public string FunctionHandler(string input, ILambdaContext context)
        {
            var log = LogManager.GetLogger(this.GetType());
            var result = input?.ToUpper();
            context.Logger.LogLine($"FunctionHandler invoked(); result: {result}");
            log.Info($"FunctionHandler invoked(); result: {result}");
            var resourceValue = IdeaQueries.ResourceManager.GetString("VoteIdea");
            context.Logger.LogLine($"VoteIdea Resource value: '{resourceValue}'");

            return result;
        }

        static void ConfigureLog4net()
        {
            Hierarchy hierarchy = (Hierarchy)LogManager.GetRepository(Assembly.GetExecutingAssembly());
            PatternLayout patternLayout = new PatternLayout();

            patternLayout.ConversionPattern = "%-4timestamp [%thread] %-5level %logger %ndc - %message%newline";
            patternLayout.ActivateOptions();

            AWSAppender appender = new AWSAppender();
            appender.Layout = patternLayout;

            // Set log group and region. Assume credentials will be found using the default profile or IAM credentials.
            appender.LogGroup = "/aws/lambda/MyFunction";
            appender.Region = "us-east-2";

            appender.ActivateOptions();
            hierarchy.Root.AddAppender(appender);

            hierarchy.Root.Level = Level.All;
            hierarchy.Configured = true;
        }
    }
}
```

**Contents of .csproj file**
```XML
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <AWSProjectType>Lambda</AWSProjectType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.Core" Version="1.1.0" />
    <PackageReference Include="Amazon.Lambda.Serialization.Json" Version="1.7.0" />
    <PackageReference Include="AWS.Logger.Log4net" Version="1.5.2" />
  </ItemGroup>
  <ItemGroup>
    <None Update="log4net.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="IdeaQueries.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>IdeaQueries.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="IdeaQueries.Designer.cs">
      <DependentUpon>IdeaQueries.resx</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>
``` 

**Contents of IdeaQueries.sql**
```XML
<?xml version="1.0" encoding="utf-8"?>
<root>
    <resheader name="resmimetype">
        <value>text/microsoft-resx</value>
    </resheader>
    <resheader name="version">
        <value>2.0</value>
    </resheader>
    <resheader name="reader">
        <value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
    </resheader>
    <resheader name="writer">
        <value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
    </resheader>
    <data name="VoteIdea" type="System.Resources.ResXFileRef, System.Windows.Forms">
        <value>VoteIdea.sql;System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089;utf-8</value>
    </data>
</root>
```

**Contents of VoteIdea.sql**
```
TEST TEST
```

***Code used to get resource value:***
```C#
var resourceValue = IdeaQueries.ResourceManager.GetString("VoteIdea");
```

Deployed the code using .NET CLI. While testing the function in AWS Console, I see the following log in CloudWatch log (note the contents of SQL file `TEST TEST` returned):
```
START RequestId: 33031ccd-d86b-42a2-92c6-958763aa122a Version: $LATEST
FunctionHandler invoked(); result: HELLO WORLD
VoteIdea Resource value: 'TEST TEST'
END RequestId: 33031ccd-d86b-42a2-92c6-958763aa122a
REPORT RequestId: 33031ccd-d86b-42a2-92c6-958763aa122a	Duration: 1106.78 ms	Billed Duration: 1200 ms	Memory Size: 256 MB	Max Memory Used: 87 MB
```

Please confirm if this issue could be closed.

Thanks,
Ashish

**Comment by CodeRevver** [comment] 2020-10-07 20:50
Hi @ashishdhingra  

Yeah I don't know - I haven't used lambda's in a while so it could have been fixed.

If the resx is referencing the file VoteIdea.sql and it's pulling back the sql AND it's running on the deployed lambda (locally it worked for me but no when deployed) then it's fixed.

**Comment by ashishdhingra** [comment] 2020-10-07 20:52
@CodeRevver Thanks for your reply. I will close this issue for now. Feel free to open a new issue in case you see the problem in future.

**Closed** 2020-10-07 20:52 UTC
Labels: bug, module/lambda-client-lib
