### ISSUE TITLE
Scheduled events

### ISSUE THREAD

**Issue by tarurar** [aws/aws-lambda-dotnet#147] opened 2017-07-30 18:13 UTC
Which package can be used to work with scheduled cloud watch events?

**Comment by Kralizek** [comment] 2017-07-31 17:31
There is no package supporting it.

#88 here I suggest a class that supports some of the information sent from CloudWatch.
#16 here there is a discussion where @normj shows possibilities and problems that need to be solved to be able to support the whole message.

**Comment by normj** [comment] 2017-08-24 00:30
Closing as duplicate of https://github.com/aws/aws-lambda-dotnet/issues/16

I understand this would be really useful, I just don't have a way yet to keep all the different possible event types coming from CloudWatch events updated all the time.

**Closed by normj** 2017-08-24 00:30 UTC
Labels: Question
