### ISSUE TITLE
Getting MissingMethodException when using standard libraries

### ISSUE THREAD

**Issue by joro550** [aws/aws-lambda-dotnet#668] opened 2020-05-13 10:18 UTC
I have a "factory" class tat sets up some dependency injection inside of my Aws Lambda:

```
var serviceProvider = new ServiceCollection()
                .AddHttpClient()
..... Other services
```

and when I run the test tool it throws back:
```
System.MissingMethodException: Method not found: 'Microsoft.Extensions.DependencyInjection.IServiceCollection Microsoft.Extensions.DependencyInjection.HttpClientFactoryServiceCollectionExtensions.AddHttpClient(Microsoft.Extensions.DependencyInjection.IServiceCollection)'.
   at Factories.ProcessorFactory.CreateProcessor()
   // Handle event method
   at Amazon.Lambda.TestTool.Runtime.LambdaExecutor.ProcessReturnAsync(ExecutionRequest request, Object lambdaReturnObject) in C:\codebuild\tmp\output\src142363207\src\Tools\LambdaTestTool\src\Amazon.Lambda.TestTool\Runtime\LambdaExecutor.cs:line 141
   at Amazon.Lambda.TestTool.Runtime.LambdaExecutor.ExecuteAsync(ExecutionRequest request) in C:\codebuild\tmp\output\src142363207\src\Tools\LambdaTestTool\src\Amazon.Lambda.TestTool\Runtime\LambdaExecutor.cs:line 62
```

Heres a dump of the `aws-lambda-tools-defaults.json`:

```
{
  "Information": [
    "This file provides default values for the deployment wizard inside Visual Studio and the AWS Lambda commands added to the .NET Core CLI.",
    "To learn more about the Lambda commands with the .NET Core CLI execute the following command at the command line in the project root directory.",
    "dotnet lambda help",
    "All the command line options for the Lambda command can be specified in this file."
  ],
  "profile": "default",
  "region": "eu-west-1",
  "configuration": "Release",
  "framework": "netcoreapp3.1",
  "function-runtime": "dotnetcore3.1",
  "function-memory-size": 256,
  "function-timeout": 30,
  "function-handler": "HandleStreamEvent"
}
```

**Comment by ckuetbach** [comment] 2020-05-15 19:33
Is there a chance, that the cause is a PublishTrimmed flag during build? https://docs.microsoft.com/de-de/dotnet/core/whats-new/dotnet-core-3-0#assembly-linking

**Comment by joro550** [comment] 2020-05-19 12:50
Sadly not - my project file is pretty ordinary:

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <AWSProjectType>Lambda</AWSProjectType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.Core" Version="1.1.0" />
    <PackageReference Include="Amazon.Lambda.Serialization.SystemTextJson" Version="1.0.0" />
    <PackageReference Include="Amazon.Lambda.DynamoDBEvents" Version="1.1.0" />
    <PackageReference Include="AWSSDK.DynamoDBv2" Version="3.3.105.14" />
    <PackageReference Include="Microsoft.AspNet.WebApi.Client" Version="5.2.7" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="3.1.3" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="3.1.3" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
  </ItemGroup>
</Project>
```

Apart from some internal nuget pacakges that is like for like

**Comment by stagha** [comment] 2020-06-05 20:57
I am having this same problem with using libraries that have a Microsoft.AspNetCore dependency. I put together a test project. It builds but throws the MissingMethodException when run via the lambda test tool. 

https://github.com/stagha/netcoreapp3.1-lambda-with-microsoft.net-dependency

Would appreciate some insight as we were forced to downgrade our lambda to .NET Core 2.1 in order to continue development. Thank you!

**Comment by Diggzinc** [comment] 2020-07-03 23:13
Recently I've faced this issue.

For me it was the usage of `Microsoft.Extensions.DependencyInjection.Abstractions` in version `3.x` that was causing trouble.
Downgrading to version `2.x` fixed the issue for me.

For you, it might be another library, but the root cause seems to be the same which is that currently the AWS Libraries compile with a version `2.x` reference for Microsoft packages such `Microsoft.Extensions.DependencyInjection.Abstractions`.

The problem then arises because the AWS Libraries say that those packages work with the transitive dependencies with versions superior or equal to `>=2.0.0`. But it seems that's not the case.
Introducing a version with a `major` change actually breaks the application (ex.: `3.x` versions), which is turn is actually _fine_ since a `major` change means that the contracts might be broken, so nothing is wrong there.

I think the best course of action would probably be to gate the transitive dependencies to use versions `>=2.0.0 and <3.0.0` on the AWS side, if someone could validate this it would be really helpful.

**Comment by stagha** [comment] 2020-07-06 22:58
It's been a while since I've been able to look at this, but I was finally able to upload a [test project](https://github.com/stagha/netcoreapp3.1-lambda-with-microsoft.net-dependency/tree/master/src/App).

I am not sure that the problem is with the AWS libraries themselves. The reason is the error ONLY occurs when running the lambda in the test tool. When uploading the same code to a deployed lambda and running it in the cloud, there are no problems.

Any ideas on what might be the problem?

**Comment by Diggzinc** [comment] 2020-07-08 21:11
I would have to take the time to dig deeper into it.

But at first glance it might me that the tool has its own set of dependencies that somehow might be conflicting with the app. I would have to check how the assembly resolution is done when the application is attached to the tool to see if my guess is correct (since I believe the tool is what provisions the "_runtime_" while testing).

But then again this is just a wild guess, so take it with a grain of salt.

**Comment by ashishdhingra** [comment] 2020-10-22 23:16
Issue similar to https://github.com/aws/aws-lambda-dotnet/issues/710

**Comment by AdnanSoftic** [comment] 2021-02-24 12:58
Are there any news on this issue? I am getting MissingMethodException when adding HttpContextAccessor using the Microsoft.Extensions.DependencyInjection package.

`services.AddHttpContextAccessor();`

Lambda works just fine when it is published but this makes it impossible to do any local debugging.

**Comment by soccerboymalloy-patriot** [comment] 2021-03-10 01:38
I was getting the same error as above, but for `Microsoft.Extensions.Hosting.IHostBuilder`, when using version 3 of the tool. I resolved that specific issue by upgrading to version 5 with a .Net 5 Container Lambda, but now I'm stuck on a new error:
```
System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<!!0> System.Net.Http.Json.HttpContentJsonExtensions.ReadFromJsonAsync(System.Net.Http.HttpContent, System.Text.Json.JsonSerializerOptions, System.Threading.CancellationToken)'.
   <... custom code ...>
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   <... custom code ...>
   at Amazon.Lambda.TestTool.Runtime.LambdaExecutor.ProcessReturnAsync(ExecutionRequest request, Object lambdaReturnObject) in C:\codebuild\tmp\output\src598299731\src\Tools\LambdaTestTool\src\Amazon.Lambda.TestTool\Runtime\LambdaExecutor.cs:line 138
   at Amazon.Lambda.TestTool.Runtime.LambdaExecutor.ExecuteAsync(ExecutionRequest request) in C:\codebuild\tmp\output\src598299731\src\Tools\LambdaTestTool\src\Amazon.Lambda.TestTool\Runtime\LambdaExecutor.cs:line 62
```

Being unable to use the testing tool is blocking adoption of Lambdas for my organization. Any update on this?

Can we consolidate this bug into either this ticket or the related one (https://github.com/aws/aws-lambda-dotnet/issues/710)?

**Comment by mabead** [comment] 2021-04-12 20:28
I was getting this error with version 0.11.1 of amazon.lambda.testtool-3.1. I have upgrade to version 0.11.3 and the problem is now gone. I can now use the lambda test tool successfully.

**Comment by ashishdhingra** [comment] 2021-04-12 20:31
This should be fixed in as part of commit https://github.com/aws/aws-lambda-dotnet/commit/adc0687af7174d1d03183a6a8dd7d90484944920, in version 0.11.3 of Lambda Test Tool.

**Closed by ashishdhingra** 2021-04-12 20:31 UTC
Labels: B, bug, module/lambda-test-tool, needs-reproduction
