### ISSUE TITLE
--msbuild-parameters not working for dotnet lambda package-ci

### ISSUE THREAD

**Issue by simon10says** [aws/aws-lambda-dotnet#663] opened 2020-05-06 14:58 UTC
I'm not sure if I'm doing this correctly. When I run `dotnet lambda package-ci` with `--msbuild-parameters`, it doesn't seems to apply to the underlying `dotnet publish`

Enclosed [AWSServerless1.zip](https://github.com/aws/aws-lambda-dotnet/files/4587515/AWSServerless1.zip) is my testing solution:
1. In the `CI.ps1`, there are 2 scripts - `dotnet lambda package-ci` and `dotnet lambda package`
2. `dotnet lambda package` with `--msbuild-parameters -p:Version=6.6.6` **will correctly** package a zip file with the dll versioned to `6.6.6`
3. However, when I run `dotnet lambda package-ci` with the same `--msbuild-parameters -p:Version=6.6.6`, the zip file in my s3 bucket **does not** version the dll correctly

Any idea why? Also, I'm running this on a Windows 10 machine

**Comment by simon10says** [comment] 2020-05-07 04:54
I've also tried `dotnet lambda deploy-serverless` with the `--msbuild-parameters` and it also doesn't work.

I'm using `Amazon Lambda Tools for .NET Core applications (4.0.0)`

**Comment by simon10says** [comment] 2020-05-07 05:42
This might be related; the `--configuration` also doesn't seems to get passed to the `dotnet publish`.

It works for `dotnet lambda package` with the following logs:
```
Executing publish command
... invoking 'dotnet publish', working folder 'D:\SampleCodes\AWSServerless1\\AWSServerless1\bin\Debug\netcoreapp3.1\publish'
... publish: Microsoft (R) Build Engine version 16.5.0+d4cbfca49 for .NET Core
... publish: Copyright (C) Microsoft Corporation. All rights reserved.
... publish:   Restore completed in 213.46 ms for D:\SampleCodes\AWSServerless1\AWSServerless1\AWSServerless1.csproj.
... publish:   AWSServerless1 -> D:\SampleCodes\AWSServerless1\AWSServerless1\bin\Debug\netcoreapp3.1\linux-x64\AWSServerless1.dll   
```
You can see from the above log that it publishes to `bin\Debug` when I execute `dotnet lambda package --configuration Debug`

However, `package-ci` and `deploy-serverless` wrongly published to `bin\Release`

**Comment by ashishdhingra** [comment] 2020-10-21 19:52
Hi @simon10says,

Good afternoon.

I was going through the backlog and came across this issue. The `--msbuild-parameters` could be ignored due to the check mentioned at the code [TemplateProcessorManager.cs](https://github.com/aws/aws-extensions-for-dotnet-cli/blob/a24f8a887530b4fadfe346b3e364929a6c407c07/src/Amazon.Lambda.Tools/TemplateProcessor/TemplateProcessorManager.cs#L230). It checks if the project is in the same directory as the CloudFormation template; if yes, then it uses any parameters there were specified on the command to build the project. I'm not sure the reason behind this, may be it has to do something with the `dotnet publish` requirement.

I do notice that your solution contains `serverless.yml` template outside (one level up) of the project directory. I copied the template to project directory and the `--msbuild-parameters` are correctly handled.
**serverless.yml**
```YML
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  TestFunction3:
    Type: AWS::Serverless::Function
    Properties:
        Runtime: dotnetcore3.1
        FunctionName: "TestFunction3"
        Handler: AWSServerless2::AWSServerless2.Function::TestFunction3
        CodeUri: '.'
        MemorySize: 128
        Role: null
        Policies:
        - AWSLambdaBasicExecutionRole
        Timeout: 30
```
**package-ci command**
```
dotnet lambda package-ci --project-location . --configuration Release --profile default ` --region us-east-2 --s3-bucket test-bucket-1a1a --template ./serverless.yml --output-template  ./serverless-output.yml --msbuild-parameters -p:Version=6.6.6
```
**Output of package-ci command**
```
Amazon Lambda Tools for .NET Core applications (4.3.0)
Project Home: https://github.com/aws/aws-extensions-for-dotnet-cli, https://github.com/aws/aws-lambda-dotnet
	
Processing CloudFormation resource TestFunction3
Initiate packaging of . for resource TestFunction3
Executing publish command
Deleted previous publish folder
... invoking 'dotnet publish', working folder '/Users/username/Downloads/AWSServerless1/AWSServerless2/./././bin/Release/netcoreapp3.1/publish'
... dotnet publish --output "/Users/username/Downloads/AWSServerless1/AWSServerless2/./././bin/Release/netcoreapp3.1/publish" --configuration "Release" --framework "netcoreapp3.1" -p:Version=6.6.6 /p:GenerateRuntimeConfigurationFiles=true --runtime linux-x64 --self-contained false 
... publish: Microsoft (R) Build Engine version 16.7.0+7fb82e5b2 for .NET
... publish: Copyright (C) Microsoft Corporation. All rights reserved.
... publish:   Determining projects to restore...
... publish:   Restored /Users/username/Downloads/AWSServerless1/AWSServerless2/AWSServerless2.csproj (in 272 ms).
... publish:   AWSServerless2 -> /Users/username/Downloads/AWSServerless1/AWSServerless2/bin/Release/netcoreapp3.1/linux-x64/AWSServerless2.dll
... publish:   AWSServerless2 -> /Users/username/Downloads/AWSServerless1/AWSServerless2/bin/Release/netcoreapp3.1/publish/
Changed permissions on published file (chmod +rx AWSServerless2.pdb).
Changed permissions on published file (chmod +rx Amazon.Lambda.Serialization.SystemTextJson.dll).
Changed permissions on published file (chmod +rx AWSServerless2.runtimeconfig.json).
Changed permissions on published file (chmod +rx Amazon.Lambda.Core.dll).
Changed permissions on published file (chmod +rx AWSServerless2.dll).
Changed permissions on published file (chmod +rx AWSServerless2.deps.json).
Zipping publish folder /Users/username/Downloads/AWSServerless1/AWSServerless2/./././bin/Release/netcoreapp3.1/publish to /var/folders/5v/klr4lq9j0rd95h4xtmydvgrwqf_g0k/T/TestFunction3-CodeUri-637388810765026120.zip
... zipping:   adding: AWSServerless2.pdb (deflated 41%)
... zipping:   adding: Amazon.Lambda.Serialization.SystemTextJson.dll (deflated 47%)
... zipping:   adding: AWSServerless2.runtimeconfig.json (deflated 23%)
... zipping:   adding: Amazon.Lambda.Core.dll (deflated 46%)
... zipping:   adding: AWSServerless2.dll (deflated 56%)
... zipping:   adding: AWSServerless2.deps.json (deflated 67%)
Created publish archive (/var/folders/5v/klr4lq9j0rd95h4xtmydvgrwqf_g0k/T/TestFunction3-CodeUri-637388810765026120.zip).
Lambda project successfully packaged: /var/folders/5v/klr4lq9j0rd95h4xtmydvgrwqf_g0k/T/TestFunction3-CodeUri-637388810765026120.zip
Uploading to S3. (Bucket: test-bucket-1a1a Key: TestFunction3-CodeUri-637388810765026120-637388810801191520.zip)
... Progress: 100%
Writing updated template: ./serverless-output.yml
```

Looks like the `--msbuild-parameters` (or any other command line parameters) are ignored if any of the projects are outside of the current `serverless.yml` directory.

Please let me know if this provides required explanation and if this issue could be closed.

Thanks,
Ashish

**Comment by ashishdhingra** [comment] 2020-10-21 20:31
Closing this as duplicate of https://github.com/aws/aws-extensions-for-dotnet-cli/issues/122.

**Closed by ashishdhingra** 2020-10-21 20:31 UTC
Labels: bug, duplicate, module/lambda-client-lib
