### ISSUE TITLE
.NET 6

### ISSUE THREAD

**Issue by IvanFarkas** [aws/aws-lambda-dotnet#889] opened 2021-07-12 13:14 UTC
What's the ETA for a .NET 6 version, please?

**Comment by martonx** [comment] 2021-07-12 13:26
As I saw at .Net 3.1
.Net 6 will be release at 2021 december. AWS LAmbda .net team will start to work after it, and they will release .Net 6 support at 2022 Q2.

**Comment by normj** [comment] 2021-07-14 17:55
I can't provide any details about upcoming releases but we do track LTS versions of language runtimes and we are tracking the .NET 6 which is an LTS version.

**Comment by IvanFarkas** [comment] 2021-07-15 16:05
Hi @normj. Thx for the wink ;-)

**Comment by IvanFarkas** [comment] 2021-07-15 16:07
@martonx Kedves Lajos! Koszonom szepen. Sejted, avagy tudod?

**Comment by ashishdhingra** [comment] 2021-07-15 18:32
Closing the issue since response has been logged.

**Closed by ashishdhingra** 2021-07-15 18:32 UTC
Labels: guidance, module/lambda-client-lib

**Comment by ivanfarkas2** [comment] 2021-07-22 22:12
**I solved the issue.**
I built a **.NET 6 docker image** that has the **.NET 6 AWS Lambda build**.
The **SAM** is published by [AWS Toolkit for VS 2019](https://marketplace.visualstudio.com/items?itemName=AmazonWebServices.AWSToolkitforVisualStudio2017).
It works great!
I wait for **NOONE**!

**Comment by ivanfarkas2** [comment] 2021-07-22 22:13
Please take your time. ;-)

**Comment by ofcoursedude** [comment] 2021-11-09 12:27
> **I solved the issue.**
> 
> I built a **.NET 6 docker image** that has the **.NET 6 AWS Lambda build**.
> 
> The **SAM** is published by [AWS Toolkit for VS 2019](https://marketplace.visualstudio.com/items?itemName=AmazonWebServices.AWSToolkitforVisualStudio2017).
> 
> It works great!
> 
> I wait for **NOONE**!

Care to share the Dockerfile?

**Comment by normj** [comment] 2021-11-09 18:22
@ofcoursedude We are working on getting the .NET 6 image published to the public ECR. If you want want to use the image today you can build the image yourself with the following directions.

* Use a PowerShell terminal
* Clone this repo
* cd into `LambdaRuntimeDockerfiles`
* Run the command `.\build.ps1 -TargetFramework net6 -Architecture amd64`

That will create an image called `dotnet6-runtime:base-image-amd64`.

**Comment by ofcoursedude** [comment] 2021-11-09 18:31
> @ofcoursedude We are working on getting the .NET 6 image published to the public ECR. If you want want to use the image today you can build the image yourself with the following directions.
> 
> 
> 
> * Use a PowerShell terminal
> 
> * Clone this repo
> 
> * cd into `LambdaRuntimeDockerfiles`
> 
> * Run the command `.\build.ps1 -TargetFramework net6 -Architecture amd64`
> 
> 
> 
> That will create an image called `dotnet6-runtime:base-image-amd64`.

Thanks, I'll give it a try. 
Is there at least a rough ETA? We are hoping to switch to net6 largely for performance reasons. If the ETA is something like a few days or weeks we'll just wait for the official image, but if it were to be months away we'd probably it in for something temporary.

**Comment by shashijeevan** [comment] 2021-11-12 04:31
> I can't provide any details about upcoming releases but we do track LTS versions of language runtimes and we are tracking the .NET 6 which is an LTS version.

@normj 
Now that we have the .Net 6 LTS version in GA, when can we expect its support in Lambda. Any specific ETA on this?

**Comment by normj** [comment] 2021-11-12 19:55
Sorry I can't give an ETA, best I can tell you it is mine and many others top focus.

**Comment by battarro** [comment] 2021-11-12 23:45
> Sorry I can't give an ETA, best I can tell you it is mine and many others top focus.

Thank you for the update.
for LTS native lambda support without , Im guessing it is also being worked on.

**Comment by TrongTheAlpaca** [comment] 2021-11-15 08:14
> @ofcoursedude We are working on getting the .NET 6 image published to the public ECR. If you want want to use the image today you can build the image yourself with the following directions.
> 
> * Use a PowerShell terminal
> * Clone this repo
> * cd into `LambdaRuntimeDockerfiles`
> * Run the command `.\build.ps1 -TargetFramework net6 -Architecture amd64`
> 
> That will create an image called `dotnet6-runtime:base-image-amd64`.

I can confirm that this works! Thanks!

**Comment by ofcoursedude** [comment] 2021-11-15 09:49
Does indeed. We have put it into our pipeline and seems to be fine - though I would obviously prefer to have official image... (at least until native support, which is the ultimate goal...)

**Comment by DerekBeattieCG** [comment] 2021-11-30 17:10
@battarro This works now, see https://github.com/jasonkochel/Net6LambdaTemplate

**Comment by Kralizek** [comment] 2021-12-01 15:14
> @ofcoursedude We are working on getting the .NET 6 image published to the public ECR. If you want want to use the image today you can build the image yourself with the following directions.
> 
> * Use a PowerShell terminal
> * Clone this repo
> * cd into `LambdaRuntimeDockerfiles`
> * Run the command `.\build.ps1 -TargetFramework net6 -Architecture amd64`
> 
> That will create an image called `dotnet6-runtime:base-image-amd64`.

Is there an issue we can track for when a .NET 6.0 base image is available on Public ECR?

**Comment by Newp** [comment] 2021-12-09 21:14
.net 6 container image has updated. https://gallery.ecr.aws/lambda/dotnet

**Comment by akospinter** [comment] 2021-12-31 16:09
@normj , thanks for working on this.
Do you have any new information about when the native .NET 6 runtime will be available?

**Comment by michaelthwaite** [comment] 2022-01-24 12:40
Is native support on the roadmap? Or is the recommendation now to roll-your-own?

**Comment by memark** [comment] 2022-01-24 12:51
I recently wrote a blog post about this. Turns out there is actually very little you need to "roll on your own" to run .NET 6 on Lambda.

https://dev.to/memark/running-a-graphql-api-in-net-6-on-aws-lambda-17oc

**Comment by michaelthwaite** [comment] 2022-01-24 13:05
@memark thanks for taking the time to write that up. Do you have a version that extracts your Serverless API element? I ask as I'm looking to simple update and deploy some existing dotnet core lambda functions that perform queue, email, event based processes and I was hoping to simply edit the runtime settings in my code and dotnet lambda deploy-function

**Comment by hounddog22030** [comment] 2022-01-24 15:38
> @memark thanks for taking the time to write that up. Do you have a version that extracts your Serverless API element? I ask as I'm looking to simple update and deploy some existing dotnet core lambda functions that perform queue, email, event based processes and I was hoping to simply edit the runtime settings in my code and dotnet lambda deploy-function

this is our version:

`FROM public.ecr.aws/lambda/dotnet:latest AS base

WORKDIR /var/task

# This COPY command copies the .NET Lambda project's build artifacts from the host machine into the image. 
# The source of the COPY should match where the .NET Lambda project publishes its build artifacts. If the Lambda function is being built 
# with the AWS .NET Lambda Tooling, the `--docker-host-build-output-dir` switch controls where the .NET Lambda project
# will be built. The .NET Lambda project templates default to having `--docker-host-build-output-dir`
# set in the aws-lambda-tools-defaults.json file to "bin/Release/net6.0/linux-x64/publish".
#
# Alternatively Docker multi-stage build could be used to build the .NET Lambda project inside the image.
# For more information on this approach checkout the project's README.md file.
COPY "bin/linux-x64/publish"  .   
`

**Comment by memark** [comment] 2022-01-24 17:07
Yup, that certainly works. Just don't forget the now added complexity of pushing /hosting/versioning your docker images. @hounddog22030

**Comment by memark** [comment] 2022-01-26 11:33
@michaelthwaite You're welcome. I'm not sure exactly what you mean by "extract your serverless api element". The article has a full working code repository attached to it, if that would help. Could you elaborate?

**Comment by normj** [comment] 2022-01-27 02:09
@memark Nice write up on using the new `Amazon.Lambda.AspNetCoreServer.Hosting` package and custom runtimes.

**Comment by wjax** [comment] 2022-02-23 09:46
Hi,

It's been several months since .NET 6 LTS is out and still there is no lambda ZIP support?
Is there a problem or maybe it is not going to happen?

Could you please update the situation?

Thanks

**Comment by petarrepac** [comment] 2022-02-23 12:10
> Hi,
> 
> It's been several months since .NET 6 LTS is out and still there is no lambda ZIP support? Is there a problem or maybe it is not going to happen?
> 
> Could you please update the situation?
> 
> Thanks

Similar to https://github.com/aws/aws-lambda-dotnet/issues/1062

**Comment by normj** [comment] 2022-02-24 17:33
It is official .NET 6 support is out. Here is the blog post for the release.

https://aws.amazon.com/blogs/compute/introducing-the-net-6-runtime-for-aws-lambda/

**Comment by petarrepac** [comment] 2022-02-24 22:20
\o/

Thank you !
